package life.genny.rules;
import life.genny.qwanda.message.QDataAnswerMessage;
import life.genny.models.GennyToken;
import life.genny.rules.QRules;
import life.genny.utils.BaseEntityUtils;
import life.genny.qwanda.Answer;
import life.genny.qwanda.entity.BaseEntity;
import life.genny.qwanda.utils.OutputParam;
import life.genny.qwandautils.KeycloakUtils;
import life.genny.qwandautils.QwandaUtils;
import life.genny.qwandautils.GennySettings;
import java.util.UUID;
import life.genny.notifications.EmailHelper;
import java.util.Arrays;

import java.util.List;
import java.util.ArrayList;

rule "IS_CLUB_PRESIDENT"
    ruleflow-group 'IsBaseEntity'
    no-loop true
    salience 1000
    when
	 	userToken : GennyToken (code != "PER_SERVICE" )
		serviceToken : GennyToken (code == "PER_SERVICE" )
		baseEntityType : String(baseEntityType.equals("QA_CLUB_PRESIDENT"))
		newBe : BaseEntity()
 		beUtils: BaseEntityUtils()
    then
        System.out.println(drools.getRule().getName() + " : Rule fired" );
 		System.out.println(drools.getRule().getName() + " newBe = " + newBe.getCode());

		retract(newBe)

end
