package life.genny.rules;


import life.genny.qwanda.message.QCmdMessage;
import life.genny.qwanda.message.QBulkMessage;
import life.genny.qwanda.message.QDataBaseEntityMessage;
import life.genny.qwanda.message.QEventMessage;
import life.genny.rules.QRules;
import life.genny.qwandautils.JsonUtils;
import org.apache.logging.log4j.Logger;


import java.util.List;
import java.util.ArrayList;
import life.genny.qwanda.entity.BaseEntity;
import life.genny.qwanda.entity.SearchEntity;
import life.genny.utils.VertxUtils;
import life.genny.utils.BaseEntityUtils;
import life.genny.models.GennyToken;
import org.kie.api.runtime.process.WorkflowProcessInstance;
import life.genny.utils.BaseEntityUtils;
import life.genny.qwandautils.GennySettings;

rule "SBE_APPLICATION"
    ruleflow-group 'GenerateSearches'
     no-loop true
    when
       not  SearchEntity (code == "SBE_APPLICATION")
        serviceToken : GennyToken( code == "PER_SERVICE")
     then
     	System.out.println("   Generate "+drools.getRule().getName() );
     	BaseEntityUtils beUtils = new BaseEntityUtils(serviceToken);

		SearchEntity searchBE = new SearchEntity(drools.getRule().getName(), "Application Detail View")

			/*Media & Downloads*/
			.addAssociatedColumn("LNK_HOST_COMPANY", "PRI_IMAGE_URL", "Company Logo")
			.addAssociatedColumn("PRI_INTERN_CODE", "PRI_IMAGE_URL", "Intern Profile Photo")
			.addAssociatedColumn("LNK_INTERNSHIP", "PRI_VIDEO_URL", "Video")
			.addAssociatedColumn("LNK_HOST_COMPANY", "PRI_LINKEDIN_URL", "Comapny LinkedIn")

			/*Internship Details*/
			.addAssociatedColumn("LNK_INTERNSHIP", "PRI_NAME", "Title")
			.addAssociatedColumn("LNK_INTERNSHIP", "LNK_SOFTWARE", "PRI_NAME", "Software To Be Used")
			.addAssociatedColumn("LNK_INTERNSHIP", "LNK_DRESS_CODE", "PRI_NAME", "Dress Code")
			.addAssociatedColumn("LNK_INTERNSHIP", "LNK_OCCUPATION", "PRI_NAME", "Internship Specialisation")
			.addAssociatedColumn("LNK_INTERNSHIP", "LNK_INDUSTRY", "PRI_NAME", "Industry")
			.addAssociatedColumn("LNK_INTERNSHIP", "LNK_WORKSITE_SELECT", "PRI_NAME", "Internship Type")
			.addAssociatedColumn("LNK_INTERNSHIP", "PRI_INTERNSHIP_START_DATE", "Internship Available From")
			.addAssociatedColumn("LNK_INTERNSHIP", "PRI_WHICH_DAYS_STRIPPED", "Days of Internship")
			.addAssociatedColumn("LNK_INTERNSHIP", "PRI_BUSINESS_HOURS", "Business Hours")
			.addAssociatedColumn("LNK_INTERNSHIP", "PRI_NO_OF_INTERNS", "Number of Opportunities")
			.addAssociatedColumn("LNK_INTERNSHIP", "PRI_INTERNSHIP_DETAILS", "Short Internship Summary")
			.addAssociatedColumn("LNK_INTERNSHIP", "PRI_ROLES_AND_RESPONSIBILITIES", "Roles and Responsibilities")
			.addAssociatedColumn("LNK_INTERNSHIP", "PRI_BASE_LEARNING_OUTCOMES", "Learning Outcomes")
			.addAssociatedColumn("LNK_INTERNSHIP", "PRI_SPECIFIC_LEARNING_OUTCOMES", "Specific Learning Outcomes")

			/*Company Details*/
			.addAssociatedColumn("LNK_INTERNSHIP", "LNK_HOST_COMPANY", "PRI_NAME", "Host Company")
			.addAssociatedColumn("LNK_INTERNSHIP", "LNK_HOST_COMPANY", "PRI_ADDRESS_FULL","Location")
			.addAssociatedColumn("LNK_INTERNSHIP", "LNK_HOST_COMPANY", "LNK_COMPANY_INDUSTRY", "PRI_NAME", "Company Industry")
			.addAssociatedColumn("LNK_INTERNSHIP", "LNK_HOST_COMPANY", "PRI_COMPANY_DESCRIPTION", "About the Company")
			.addAssociatedColumn("LNK_INTERNSHIP", "LNK_HOST_COMPANY", "PRI_ADDRESS_LATITUDE", "Lat")
			.addAssociatedColumn("LNK_INTERNSHIP", "LNK_HOST_COMPANY", "PRI_ADDRESS_LONGITUDE", "Lng")

			/*Supervisor Details*/
			.addAssociatedColumn("LNK_INTERNSHIP","LNK_INTERN_SUPERVISOR", "PRI_IMAGE_URL", "Supervisor Profile Photo")
			.addAssociatedColumn("LNK_INTERNSHIP","LNK_INTERN_SUPERVISOR", "PRI_NAME", "Supervisor Name")
			.addAssociatedColumn("LNK_INTERNSHIP","LNK_INTERN_SUPERVISOR", "PRI_FIRSTNAME", "Supervisor First Name")
			.addAssociatedColumn("LNK_INTERNSHIP","LNK_INTERN_SUPERVISOR", "PRI_JOB_TITLE", "Position")
			.addAssociatedColumn("LNK_INTERNSHIP","LNK_INTERN_SUPERVISOR", "PRI_EMAIL", "Email")
			.addAssociatedColumn("LNK_INTERNSHIP","LNK_INTERN_SUPERVISOR", "PRI_MOBILE", "Phone Number")
			.addAssociatedColumn("LNK_INTERNSHIP","LNK_INTERN_SUPERVISOR", "PRI_LINKEDIN_URL", "LinkedIn")
			.addAssociatedColumn("LNK_INTERNSHIP","LNK_INTERN_SUPERVISOR", "PRI_BIO", "About the Supervisor")

			/*Intern Detail*/
			.addAssociatedColumn("PRI_INTERN_CODE","PRI_NAME", "Intern Name")
			.addAssociatedColumn("PRI_INTERN_CODE","PRI_ASSOC_INDUSTRY", "Industry")
			.addAssociatedColumn("PRI_INTERN_CODE","PRI_ASSOC_OCCUPATION", "Occupation")
			.addAssociatedColumn("PRI_INTERN_CODE", "PRI_LINKEDIN_URL", "Intern LinkedIn")

			/*Agent Details*/
			.addAssociatedColumn("PRI_INTERN_CODE","LNK_AGENT", "PRI_IMAGE_URL", "Agent Image")
			.addAssociatedColumn("PRI_INTERN_CODE","LNK_AGENT", "PRI_NAME", "Agent Name")

			.setDisplayMode("DETAIL_VIEW:APPLICATION")
			.setPageStart(0)
			.setPageSize(GennySettings.defaultPageSize);

		searchBE.setRealm(serviceToken.getRealm());
		insert(searchBE);
		VertxUtils.putObject(serviceToken.getRealm(), "", searchBE.getCode(), searchBE, serviceToken.getToken());

end
