package life.genny.rules;

import life.genny.qwanda.message.QDataAnswerMessage;
import life.genny.models.GennyToken;
import life.genny.rules.QRules;
import life.genny.utils.BaseEntityUtils;
import life.genny.qwanda.Answer;
import life.genny.qwanda.entity.BaseEntity;
import life.genny.qwanda.utils.OutputParam;
import java.util.List;
import java.util.ArrayList;

import io.vertx.core.json.JsonObject;
import life.genny.qwanda.message.QDataBaseEntityMessage;
import life.genny.qwanda.message.QEventBtnClickMessage;
import life.genny.models.GennyToken;
import life.genny.utils.VertxUtils;
import life.genny.qwanda.utils.OutputParam;
import life.genny.qwanda.message.QDataAskMessage;
import life.genny.qwanda.message.QScheduleMessage;
import life.genny.utils.BaseEntityUtils;
import life.genny.utils.QuestionUtils;
import life.genny.qwandautils.JsonUtils;
import java.util.ArrayList;
import java.util.List;
import life.genny.qwanda.message.QEventMessage;
import life.genny.qwanda.message.QScheduleMessage;
import life.genny.utils.BucketUtils;
import life.genny.utils.TableUtils;
import life.genny.models.ThemePosition;
import life.genny.models.ThemeAttributeType;
import life.genny.qwandautils.GennySettings;

rule "TRIGGER_PRI_CARD_STATUS_ORANGE"
    ruleflow-group 'EventProcessing'
    no-loop true
    salience 10
    when
   		$message : QEventMessage(data.code == "SCHEDULE_ORANGE" || data.code == "SCHEDULE_SHORTLIST_ORANGE")
   		userToken : GennyToken  ()
		serviceToken : GennyToken (code == "PER_SERVICE" )

     then
 		System.out.println("TRIGGER_PRI_CARD_STATUS_ORANGE: Rule fired" );
 		
 		System.out.println("Current Time is "+LocalDateTime.now());
		
		String targetCode = $message.getData().getTargetCode();
		System.out.println("targetCode: " +targetCode);
		
		BaseEntityUtils beUtils = new BaseEntityUtils(serviceToken, userToken);
		
		Answer answerColour = new Answer(serviceToken.getUserCode(), targetCode , "PRI_STATUS_COLOR", "warning");
		beUtils.saveAnswer(answerColour);
		System.out.println("Answer done" +answerColour);
		
		VertxUtils.sendToFrontEnd(userToken, answerColour);
		System.out.println("sendToFrontEnd done");
		
		
		BaseEntity targetBE  = beUtils.getBaseEntityByCode(targetCode);
		
		QDataBaseEntityMessage msg = new QDataBaseEntityMessage(targetBE);
		msg.setToken(userToken.getToken());
		
		
		String[] rxList = new String[2];
		rxList[0] = "SUPERUSER";
		rxList[1] = "PER_5A666E64-021F-48CE-8111-BE3D66901F9C";
		msg.setRecipientCodeArray(rxList);
		
		/*VertxUtils.writeMsg("webcmds", JsonUtils.toJson(msg));*/
		VertxUtils.writeMsg("project", JsonUtils.toJson(msg));
		System.out.println("writeMsg done");
		

		retract($message)


end
