package life.genny.rules;

rule "IMPORTS"
    ruleflow-group 'GenerateCapabilities'
     salience 1000000
     no-loop true
    when
    then
    end

/* java.io */
import java.io.IOException;

/* java.util */
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.HashMap;

/* life.genny.model */
import life.genny.model.OutputParamTreeSet;

/* life.genny.models */
import life.genny.models.GennyToken;
import life.genny.models.Frame3;
import life.genny.models.FramePosition;
import life.genny.models.Theme;
import life.genny.models.ThemeAttributeType;

/* life.genny.qwanda */
import life.genny.qwanda.Answer;
import life.genny.qwanda.Ask;
import life.genny.qwanda.Question;
import life.genny.qwanda.VisualControlType;

/* life.genny.qwanda.attribute */
import life.genny.qwanda.attribute.Attribute;

/* life.genny.qwanda.datatype */
import life.genny.qwanda.datatype.DataType;
import life.genny.qwanda.datatype.CapabilityMode;

/* life.genny.qwanda.entity */
import life.genny.qwanda.entity.BaseEntity;
import life.genny.qwanda.entity.SearchEntity;

/* life.genny.qwanda.message */
import life.genny.qwanda.message.QBulkMessage;
import life.genny.qwanda.message.QCmdMessage;
import life.genny.qwanda.message.QDataAnswerMessage;
import life.genny.qwanda.message.QDataAskMessage;
import life.genny.qwanda.message.QDataBaseEntityMessage;
import life.genny.qwanda.message.QEventMessage;

/* life.genny.qwandautils */
import life.genny.qwandautils.GennySettings;
import life.genny.qwandautils.JsonUtils;
import life.genny.qwandautils.QwandaUtils;

/* life.genny.rules */
import life.genny.rules.QRules;

/* life.genny.utils */
import life.genny.utils.BaseEntityUtils;
import life.genny.utils.CapabilityUtils;
import life.genny.utils.TableUtils;
import life.genny.utils.VertxUtils;
import life.genny.utils.FrameUtils2;

/* org.apache.logging.log4j */
import org.apache.logging.log4j.Logger;

/* org.drools.core.spi */
import org.drools.core.spi.KnowledgeHelper;

/* org.kie.api.runtime.process */
import org.kie.api.runtime.process.WorkflowProcessInstance;

/* org.apache.commons.lang3.text */
import org.apache.commons.lang3.text.WordUtils;

/* io.vertx.core.json */
import io.vertx.core.json.JsonObject;

/* java.lang.reflect */
import java.lang.reflect.Type;

/* com.google.gson.reflect */
import com.google.gson.reflect.TypeToken;

