package life.genny.rules;
import io.vertx.core.json.JsonObject;
import life.genny.qwanda.message.QDataBaseEntityMessage;
import life.genny.qwanda.message.QEventBtnClickMessage;
import life.genny.models.GennyToken;
import life.genny.utils.VertxUtils;
import life.genny.qwanda.utils.OutputParam;
import life.genny.qwanda.message.QDataAskMessage;
import life.genny.utils.BaseEntityUtils;
import life.genny.utils.QuestionUtils;
import life.genny.qwandautils.JsonUtils;
import java.util.ArrayList;
import java.util.List;

rule "CLICK_HC_SERVICES_AGREEMENT"
    ruleflow-group 'EventProcessing'
		salience 1000
    no-loop
    when
		$message : QEventMessage(data.code == "ACT_PRI_EVENT_HC_SERVICES_AGREEMENT_UNVALIDATED")
		userToken : GennyToken (code != "PER_SERVICE" )
		serviceToken : GennyToken (code == "PER_SERVICE" )
		output : OutputParam()
		ruleDetails : RuleDetails()

    then
		System.out.println("Processing HC SERVICES AGREEMENT : " + $message );
		System.out.println(ruleDetails+" "+drools.getRule().getName()+" Processing : " + $message );
		
		BaseEntityUtils beUtils = new BaseEntityUtils(serviceToken);
		
		/* Grab the BE's for the HCR and HC */
		String user = userToken.getUserCode();
		System.out.println("Agreement Doc User: " + user);
		
		String hcCode = "";
		
		if(user != null) {
				BaseEntity HCRBe = beUtils.getBaseEntityByCode(user);
				System.out.println("HCRBe :: " + HCRBe);
				
				if(HCRBe != null) {
				 		hcCode = HCRBe.getValue("LNK_HOST_COMPANY", null);
						System.out.println("hcCode = " + hcCode);
						
						if(hcCode != null) {
								hcCode = hcCode.replace("\"", "").replace("[", "").replace("]", "");
								System.out.println("hcCode  :: " + hcCode);	
						} else {
							System.out.println("ERROR: Null hcCode");
						}
				} else {
					System.out.println("ERROR: Null HCRBe");
				}
		} else {
			System.out.println("ERROR: Null user");
		}
		
		String workflowSignalCode = "HC_SERVICES";

		output.setAskSourceCode(user);
		output.setTypeOfResult("SIGNAL");
		output.setResultCode("START_"+workflowSignalCode);
		output.setTargetCode($message.getData().getTargetCode());
		output.setSuitCase(hcCode);

	
		System.out.println("START SIGNAL: " +workflowSignalCode);
		System.out.println("STARTING HC SERVICES AGREEMENT WITH: " +output);
	
		retract($message);
	end
