package life.genny.rules;
import io.vertx.core.json.JsonObject;
import life.genny.qwanda.message.QDataBaseEntityMessage;
import life.genny.qwanda.message.QEventBtnClickMessage;
import life.genny.models.GennyToken;
import life.genny.utils.VertxUtils;
import life.genny.qwanda.utils.OutputParam;
import life.genny.qwanda.message.QDataAskMessage;
import life.genny.utils.BaseEntityUtils;
import life.genny.utils.QuestionUtils;
import life.genny.qwandautils.JsonUtils;
import life.genny.utils.TableUtils;
import java.util.ArrayList;
import java.util.List;
import life.genny.qwanda.message.QEventMessage;
import life.genny.utils.BucketUtils;
import life.genny.models.ThemePosition;
import life.genny.models.ThemeAttributeType;
import life.genny.model.NodeStatus;
import life.genny.qwanda.Answer;


rule "EASY_CLICK_EVENT_ONHOLD"
    ruleflow-group 'EventProcessing'
		salience 2
    no-loop
    when
		$message : QEventMessage(data.code matches "ACT_PRI_EVENT_ONHOLD_APPLICATION")
		userToken : GennyToken (code != "PER_SERVICE" )
		serviceToken : GennyToken (code == "PER_SERVICE" )
		output : OutputParam( )
		ruleDetails : RuleDetails()
    then
		System.out.println("Processing EASY CLICK EVENT ONHOLD : " + $message );

		
		System.out.println(ruleDetails+" "+drools.getRule().getName()+" Processing : " + $message );
		
		/*
		code: "ACT_PRI_EVENT_ONHOLD_APPLICATION"
		parentCode: "SBE_INPROGRESS_APPLICATIONS_5B54BC48-E0D3-4867-B7AE-748834029C30"
		targetCode: "APP_FCB876B5-6CE9-49B6-A692-59E43EF75544"
		*/
		
		String targetCode = $message.getData().getTargetCode();		/* get targetCode e.g. APP_FCB876B5-6CE9-49B6-A692-59E43EF75544  */ 	
		String parentCode = $message.getData().getParentCode(); 	/* get parentcode SBE e.g. SBE_INPROGRESS_XXXXX  */ 
		System.out.println("targetCode: " +targetCode);
		System.out.println("parentCode: " +parentCode);
		
		output.setTypeOfResult("SIGNAL");
		output.setResultCode("START_APPLICATION_MOVEMENT");
		output.setTargetCode(targetCode);
		output.setSuitCase("ONHOLD");
	
		retract( $message);
	end
