package life.genny.rules;
import io.vertx.core.json.JsonObject;
import life.genny.qwanda.message.QDataBaseEntityMessage;
import life.genny.qwanda.message.QEventBtnClickMessage;
import life.genny.models.GennyToken;
import life.genny.utils.VertxUtils;
import life.genny.qwanda.utils.OutputParam;
import life.genny.qwanda.message.QDataAskMessage;
import life.genny.utils.BaseEntityUtils;
import life.genny.utils.QuestionUtils;
import life.genny.qwandautils.JsonUtils;
import life.genny.utils.TableUtils;
import java.util.ArrayList;
import java.util.List;
import life.genny.qwanda.message.QEventMessage;
import life.genny.utils.BucketUtils;
import life.genny.models.ThemePosition;
import life.genny.models.ThemeAttributeType;
import life.genny.model.NodeStatus;
import life.genny.qwanda.Answer;


rule "EASY_CLICK_EVENT_REJECT"
    ruleflow-group 'EventProcessing'
		salience 2
    no-loop
    when
		$message : QEventMessage(data.code matches "ACT_PRI_EVENT_REJECT_APPLICATION" ||
                                    data.code matches "ACT_PRI_EVENT_REJECT_APPLY" ||
                                    data.code matches "ACT_PRI_EVENT_REJECT_SHORTLIST" ||
                                    data.code matches "ACT_PRI_EVENT_REJECT_INTERVIEW" )
		userToken : GennyToken (code != "PER_SERVICE" )
		serviceToken : GennyToken (code == "PER_SERVICE" )
		output : OutputParam( )
		ruleDetails : RuleDetails()
		beUtils : BaseEntityUtils()
    then
		System.out.println("Processing EASY CLICK EVENT REJECT : " + $message );
		System.out.println(ruleDetails+" "+drools.getRule().getName()+" Processing : " + $message );
		
		
		/*
		code: "ACT_PRI_EVENT_REJECT_APPLICATION"
		parentCode: "SBE_INPROGRESS_APPLICATIONS_5B54BC48-E0D3-4867-B7AE-748834029C30"
		targetCode: "APP_FCB876B5-6CE9-49B6-A692-59E43EF75544"
		*/
		
		String targetCode = $message.getData().getTargetCode();		/* get targetCode e.g. APP_FCB876B5-6CE9-49B6-A692-59E43EF75544  */ 	
		String parentCode = $message.getData().getParentCode(); 	/* get parentcode SBE e.g. SBE_INPROGRESS_XXXXX  */ 
		System.out.println("targetCode: " +targetCode);
		System.out.println("parentCode: " +parentCode);

		if (targetCode.startsWith("PER_")) {
			/*
			This means we are coming from an intern detail view
			and must find the application to push through
			*/
			String searchCode = $message.getData().getParentCode();
			SearchEntity searchBE = VertxUtils.getObject(beUtils.getGennyToken().getRealm(), "", searchCode, SearchEntity.class, beUtils.getGennyToken().getToken());

			EntityAttribute dropdownTarget = searchBE.findEntityAttribute("SCH_DROPDOWN_TARGET").orElse(null);
			System.out.println("dropdownTarget = " + dropdownTarget);
			if (dropdownTarget == null) {
				System.out.println("dropdownTarget is null");
			} else {
				targetCode = dropdownTarget.getValue();
			}
		}
		System.out.println("targetCode = " + targetCode);
		
		BaseEntity appBe = beUtils.getBaseEntityByCode(targetCode);
		System.out.println("appBe = " + appBe);
		
		/* ========== Remove the Applications from the Intern and Internship ========== */
		String intern = appBe.getValue("PRI_INTERN_CODE", null);
		System.out.println("intern = " +intern);
		
		String internship = appBe.getValue("LNK_INTERNSHIP", null);
		internship = internship.replace("\"", "").replace("[", "").replace("]", "");
		System.out.println("internship = " +internship);
		
		beUtils.removeQuantumLinkElement(userToken.getUserCode(), intern, targetCode, "LNK_APPLICATIONS");
		beUtils.removeQuantumLinkElement(userToken.getUserCode(), internship, targetCode, "LNK_APPLICATIONS");
		/* ============================================================================ */
		
		
		output.setTypeOfResult("SIGNAL");
		output.setResultCode("START_APPLICATION_MOVEMENT");
		output.setTargetCode(targetCode);
		output.setSuitCase("REJECT");

		String code = $message.getData().getCode();
		/* if (code.equals("ACT_PRI_EVENT_REJECT_SHORTLIST") || code.equals("ACT_PRI_EVENT_REJECT_APPLY") || code.equals("ACT_PRI_EVENT_REJECT_INTERVIEW")) { */
		/* 	output.setLuggage("PROCESS"); */
		/* } */
		output.setLuggage("PROCESS");
	
		retract( $message);
	end
