package life.genny.rules;
import io.vertx.core.json.JsonObject;
import life.genny.qwanda.message.QDataBaseEntityMessage;
import life.genny.qwanda.message.QEventBtnClickMessage;
import life.genny.models.GennyToken;
import life.genny.utils.VertxUtils;
import life.genny.qwanda.utils.OutputParam;
import life.genny.qwanda.message.QDataAskMessage;
import life.genny.utils.BaseEntityUtils;
import life.genny.utils.QuestionUtils;
import life.genny.qwandautils.JsonUtils;
import java.util.ArrayList;
import java.util.List;
import life.genny.qwanda.message.QEventMessage;
import life.genny.utils.BucketUtils;
import life.genny.models.ThemePosition;
import life.genny.models.ThemeAttributeType;
import life.genny.model.NodeStatus;

rule "MOVE_BUCKET_CLICK_EVENT_REJECT"
    ruleflow-group 'EventProcessing'
		salience 2
    no-loop
    when
		$message : QEventMessage(data.code matches "ACT_PRI_EVENT_REJECT_APPLICATION")
		userToken : GennyToken (code != "PER_SERVICE" )
		serviceToken : GennyToken (code == "PER_SERVICE" )
		output : OutputParam( )
		ruleDetails : RuleDetails()
    then
		System.out.println("Processing SHORTLIST CLICK EVENT : " + $message );

		
		System.out.println(ruleDetails+" "+drools.getRule().getName()+" Processing : " + $message );
		
		/*
		code: "ACT_PRI_EVENT_REJECT_APPLICATION"
		parentCode: "SBE_INPROGRESS_APPLICATIONS_5B54BC48-E0D3-4867-B7AE-748834029C30"
		targetCode: "APP_FCB876B5-6CE9-49B6-A692-59E43EF75544"
		*/
		
		String code = $message.getData().getCode(); 
		String workflowSignalCode = "REJECT";
	
	
		String parentCode = $message.getData().getParentCode(); 	/* get parentcode SBE e.g. SBE_SHORTLISTED_XXXXX  */ 
		System.out.println("parentCode: " +parentCode);
		
		String[] parentSplit = parentCode.split("_");
        
        int size = parentSplit.length;
        System.out.println("size: " +size);
        
        String key = "";
    
        if (size == 3) {
                key = parentSplit[1];
                System.out.println("typeOf: " +typeOf);
        } else {
        	System.out.println("ERROR: Larger string than expected = " +parentCode);
        }
        
        
        output.setTypeOfResult("SIGNAL");											/* SIGNAL */
		output.setResultCode("START_"+workflowSignalCode);							/* START_REJECT */
		output.setTargetCode($message.getData().getTargetCode());					/* APP_FCB876B5-6CE9-49B6-A692-59E43EF75544 */
		output.setSuitCase(key);													/* INPROGRESS */
        
		
		String workflowBeCode = $message.getData().getTargetCode();
		System.out.println("$$$$$$$$$$$$$$$$$$$$$$$$ workflowBeCode: " + workflowBeCode);
		
		System.out.println("$$$$$$$$$$$$$$$$$$$$$$$$ targetCode: " + output.getTargetCode());
		
		SessionFacts facts = new SessionFacts(serviceToken, userToken, output.getTargetCode());
		
		System.out.println("START SIGNAL: " +workflowSignalCode);
		System.out.println("REJECTING APPLICATION NOW WITH: " +output);
	
	
		retract( $message);
	end
