package life.genny.rules;

import life.genny.qwanda.message.QEventMessage;
import life.genny.models.GennyToken;
import life.genny.utils.VertxUtils;
import io.vertx.core.json.JsonObject;
import life.genny.qwanda.utils.OutputParam;
import org.apache.commons.lang3.StringUtils;
import life.genny.qwanda.message.QCmdMessage;
import life.genny.utils.VertxUtils;


rule "HELPER_EMAIL_NOTIFICATION_EVENT"
    ruleflow-group 'EventProcessing'
		salience 2
    no-loop
    when
		userToken : GennyToken (code != "PER_SERVICE" )
		serviceToken : GennyToken (code == "PER_SERVICE" )
		output : OutputParam()
		newBe : BaseEntity()
		
    then

		System.out.println("### HELPER_EMAIL_NOTIFICATION_EVENT: Rule fired ###");
 		System.out.println("HAVE_ABN: newBe = " + newBe);
 		
 		System.out.println("### START EMAIL PROCESS ###");
 		
 		retract(newBe)
 	end
