package life.genny.rules;
import life.genny.qwanda.message.QEventMessage;
import life.genny.models.GennyToken;
import life.genny.utils.VertxUtils;
import io.vertx.core.json.JsonObject;
import life.genny.qwanda.utils.OutputParam;
import life.genny.qwanda.rule.RuleDetails;
import java.util.HashMap;
import java.util.Map;
import com.google.gson.reflect.TypeToken;
import java.lang.reflect.Type;
import org.apache.commons.lang3.StringUtils;

rule "SEND_DETAIL_VIEW"
	ruleflow-group 'EventProcessing'
	no-loop
	salience 9500
	when
		$message : QEventMessage((data.code == "QUE_SUBMIT"))
		userToken : GennyToken (code != "PER_SERVICE" )
		serviceToken : GennyToken( code == "PER_SERVICE")
		output : OutputParam( )
	
	then
		System.out.println(drools.getRule().getName() + " triggered");
		BaseEntityUtils beUtils = new BaseEntityUtils(serviceToken, userToken);

		String code = $message.getData().getCode();

		String questionCode = $message.getData().getParentCode();
		String targetCode = $message.getData().getTargetCode();

		/* System.out.println("questionCode  ::  " + questionCode);
		System.out.println("targetCode  ::  " + questionCode); */

		if(questionCode != null && !questionCode.isEmpty()){

			Map<String, String> displayCodes = VertxUtils.getMap(serviceToken.getRealm(), "", "DISPLAY_CODES");

			if(displayCodes != null && !displayCodes.isEmpty()){
				
				if(displayCodes.containsKey(questionCode)){
			
					String displayType = displayCodes.get(questionCode);
					
					if(displayType != null && !displayType.isEmpty()){

						if(displayType.equals("DETAIL")){
						
							/* extract the searchCode from questionCode */
							String sbeCode = StringUtils.substringBetween(questionCode, "QUE_", "_GRP");
							System.out.println("sbeCode  :: " + sbeCode);

							if(targetCode != null && !targetCode.isEmpty()){
								TableUtils.searchTable(beUtils, "SBE_"+sbeCode, true, "PRI_CODE", targetCode);
							}
							
						}
					}
				}
			}
		}else{
			System.out.println("Parent code is null in event message");
		}
		retract( $message);
end
