package life.genny.rules;

import life.genny.qwanda.message.QEventMessage;
import life.genny.models.GennyToken;
import life.genny.utils.VertxUtils;
import io.vertx.core.json.JsonObject;
import life.genny.qwanda.utils.OutputParam;
import org.apache.commons.lang3.StringUtils;
import life.genny.qwanda.message.QCmdMessage;
import life.genny.utils.VertxUtils;


rule "AGREE_TO_MEETING_CLICK_EVENT"
    ruleflow-group 'EventProcessing'
		salience 2
    no-loop
    when
		$message : QEventMessage(data.code matches "ACT_MENTOR_MEETING_AGREE" || data.code matches "ACT_MENTOR_MENTORING_AGREE" || data.code matches "ACT_MENTEE_MENTORING_AGREE" 
								|| data.code matches "ACT_MEETING_REQUEST" || data.code matches "ACT_MENTORING_TIME_AGREE" || data.code matches "ACT_VERIFY_MENTEE")
		userToken : GennyToken (code != "PER_SERVICE" )
		serviceToken : GennyToken (code == "PER_SERVICE" )
		output : OutputParam( )
 		ruleDetails : RuleDetails()
		beUtils : BaseEntityUtils()
    then

		System.out.println(drools.getRule().getName() + " - Rule fired");

		String code = $message.getData().getCode();
		System.out.println("code: " +code);

		String user = userToken.getUserCode();
		System.out.println("user: " + user);
		
		String workflowSignalCode = null;
		switch (code) {
		case "ACT_MENTOR_MEETING_AGREE":
		    workflowSignalCode = "START_AGREE_TO_MEETING";
		    System.out.println("########workflowSignalCode : "+ workflowSignalCode);
			output.setTargetCode(user);
		    break;
		case "ACT_MENTOR_MENTORING_AGREE":
		    workflowSignalCode = "START_AGREE_TO_MENTORING";
		    System.out.println("########workflowSignalCode : "+ workflowSignalCode);
			output.setTargetCode(user);
		    break;
		case "ACT_MENTEE_MENTORING_AGREE":
		    workflowSignalCode = "START_AGREE_TO_MENTORING_MENTEE";
		    System.out.println("########workflowSignalCode : "+ workflowSignalCode);
			output.setTargetCode(user);
		    break;
		case "ACT_MEETING_REQUEST":
		    workflowSignalCode = "START_MEETING_REQUEST";
		    System.out.println("########workflowSignalCode : "+ workflowSignalCode);
			output.setTargetCode(user);
		    break;
		case "ACT_MENTORING_TIME_AGREE":
		    workflowSignalCode = "START_MENTORING_TIME_AGREE";
		    System.out.println("########workflowSignalCode : "+ workflowSignalCode);
			output.setTargetCode(user);
		    break;
		case "ACT_VERIFY_MENTEE":
		   String mentorCode = $message.getData().getParentCode();
			System.out.println("mentorCode: " +mentorCode);
			String uuid = UUID.randomUUID().toString().toUpperCase();
			String newCode = "RSP_"+uuid;
			System.out.println("newCode = " + newCode);
			BaseEntity defBE = beUtils.getDEFByCode("DEF_RESPONSE");
			newCode = newCode.toUpperCase();
			BaseEntity responseBe = beUtils.create(defBE, newCode, newCode);
			responseBe = beUtils.saveAnswer(new Answer(userToken.getUserCode(), responseBe.getCode() ,"PRI_RESPONSE_FROM", user));
			responseBe = beUtils.saveAnswer(new Answer(userToken.getUserCode(), responseBe.getCode() ,"PRI_RESPONSE_TO", mentorCode));

		    workflowSignalCode = "START_VERIFY_MENTEE";
		    System.out.println("########workflowSignalCode : "+ workflowSignalCode);
			output.setTargetCode(responseBe.getCode());
		    break;
		}
		
        /* Set result */
        output.setTypeOfResult("SIGNAL");
		output.setResultCode(workflowSignalCode);
		output.setAskSourceCode(user);
		retract( $message);
	end
