package life.genny.rules;

global life.genny.qwanda.message.QBulkMessage payload;

rule "SEND_SIDEBAR_AGENT"
	ruleflow-group 'SendAsks'
	salience 10
	no-loop true
	when
		userToken : GennyToken (code != "PER_SERVICE" )
		serviceToken : GennyToken( code == "PER_SERVICE")
		/* allowed : Allowed(code == "AGENT") */
		beUtils : BaseEntityUtils()
	
	then
		System.out.println(drools.getRule().getName() + " triggered");

		System.out.println("ServiceToken Realm = " + serviceToken.getRealm());
		System.out.println("UserToken Realm = " + userToken.getRealm());

		/* get the sidebar ask from cache */
		Ask sidebarAsk = VertxUtils.getObject(serviceToken.getRealm(), "", "SIDEBAR_AGENT", Ask.class, serviceToken.getToken());

		if(sidebarAsk == null){
			System.err.println("sidebarAsk is not in cache");
		}else{
			
			String json = JsonUtils.toJson(sidebarAsk);
			json = json.replaceAll("PER_SERVICE", userToken.getUserCode());

			sidebarAsk = JsonUtils.fromJson(json, Ask.class);
			/* send the sidebar asks */
			QDataAskMessage askMsg = new QDataAskMessage(sidebarAsk);
			askMsg.setToken(userToken.getToken());
			VertxUtils.writeMsg("webcmds", askMsg);
		}
end
