package life.genny.rules;
import java.util.ArrayList;
import life.genny.qwandautils.JsonUtils;
import life.genny.qwanda.utils.OutputParam;
import life.genny.qwanda.message.QDataAskMessage;
import life.genny.qwanda.message.QEventMessage;
import life.genny.models.GennyToken;
import life.genny.utils.VertxUtils;
import io.vertx.core.json.JsonObject;
import life.genny.qwanda.utils.OutputParam;
import life.genny.qwanda.message.MessageData;
import life.genny.utils.BucketUtils;
import life.genny.models.ThemePosition;
import life.genny.models.ThemeAttributeType;
import life.genny.utils.TableUtils;
import org.drools.core.spi.KnowledgeHelper;
import life.genny.qwanda.datatype.Allowed;

rule "INTERN_DETAIL_VIEW"
	ruleflow-group 'DetailView'
	salience 6
	when
		$message : QEventMessage(	(data.targetCode matches "PER_.*" && 
									(
										data.parentCode matches "SBE_INTERNS_.*" ||
										data.parentCode matches "SBE_AVAILABLE_INTERNS_.*" ||
										data.parentCode matches "QUE_INTERN_GRP" ||
										data.parentCode matches "SBE_SUMMARY_INTERNS_.*" 
									))
									
									||
									
									( data.code matches "LNK_DETAIL"  && data.rootCode matches "COL_PRI_INTERN_CODE__.*" && data.targetCode matches "PER_.*" )
								)
		userToken : GennyToken (code != "PER_SERVICE" )
		serviceToken : GennyToken( code == "PER_SERVICE")
		output : OutputParam( )

	then
	
		/*
		{
 			code: 'LNK_DETAIL',
  			rootCode: linkCode,
  			targetCode: baseEntityCode
		}
		*/
		
		System.out.println(drools.getRule().getName() + " triggered");
		BaseEntityUtils beUtils = new BaseEntityUtils(serviceToken, userToken);

		MessageData data = $message.getData();
		String targetCode = data.getTargetCode();
		System.out.println("Entry TARGET code ::  " + targetCode);

		if(targetCode != null){

			long totalTime = TableUtils.searchTable(beUtils,"SBE_INTERN", true, "PRI_CODE", targetCode);
			System.out.println("total took " + (totalTime) + " ms"); 

		}else{
			System.out.println("TARGET code is null. Check FE console !");

		}

		output.setTypeOfResult("NONE");
		output.setResultCode("NONE");  /* dont display anything new */
		retract( $message);

end
