package life.genny.rules;


import life.genny.qwanda.message.QCmdMessage;
import life.genny.qwanda.message.QBulkMessage;
import life.genny.qwanda.message.QDataBaseEntityMessage;
import life.genny.qwanda.message.QEventMessage;
import life.genny.rules.QRules;
import life.genny.qwandautils.JsonUtils;
import org.apache.logging.log4j.Logger;


import java.util.List;
import java.util.ArrayList;
import life.genny.qwanda.entity.BaseEntity;
import life.genny.qwanda.entity.SearchEntity;
import life.genny.utils.VertxUtils;
import life.genny.utils.BaseEntityUtils;
import life.genny.models.GennyToken;
import org.kie.api.runtime.process.WorkflowProcessInstance;
import life.genny.utils.BaseEntityUtils;
import life.genny.qwandautils.GennySettings;

rule "SBE_APPLICATIONS_INPROGRESS"
    ruleflow-group 'GenerateSearches'
     no-loop true
    when
       not  SearchEntity (code == "SBE_APPLICATIONS_INPROGRESS")
        serviceToken : GennyToken( code == "PER_SERVICE")
     then
     	System.out.println("   Generate "+drools.getRule().getName() );

      SearchEntity searchBE = new SearchEntity(drools.getRule().getName(), "Inprogress Applications")
                              .addSort("PRI_CREATED", "Created", SearchEntity.Sort.DESC)
                              .addFilter("PRI_CODE", SearchEntity.StringFilter.LIKE, "APP_%")
                              .addFilter("PRI_STATUS", SearchEntity.StringFilter.EQUAL, "PROGRESS")
                              .addFilter("PRI_DISABLED", false)

                            	.addColumn("PRI_NAME", "Name")
                              .addColumn("PRI_CODE", "Code")
                              .addColumn("PRI_START_DATE","Start Date")
                              .addColumn("PRI_END_DATE","End Date")
                              .addColumn("PRI_ASSOC_DURATION", "DurationWeeks")
                              .addColumn("PRI_DAYS_PER_WEEK","DPW") 
                              .addColumn("LNK_DAYS_PER_WEEK", "LNK Days Per Week")
                              .addColumn("LNK_INTERNSHIP_DURATION", "LNK Internship Duration") 
                              .setPageStart(0)
                              .setPageSize(1000);

      searchBE.setRealm(serviceToken.getRealm());

      insert(searchBE);
      VertxUtils.putObject(serviceToken.getRealm(), "", searchBE.getCode(), searchBE, serviceToken.getToken());

end
