package life.genny.rules;


import life.genny.qwanda.message.QCmdMessage;
import life.genny.qwanda.message.QBulkMessage;
import life.genny.qwanda.message.QDataBaseEntityMessage;
import life.genny.qwanda.message.QEventMessage;
import life.genny.rules.QRules;
import life.genny.qwandautils.JsonUtils;
import org.apache.logging.log4j.Logger;


import java.util.List;
import java.util.ArrayList;
import life.genny.qwanda.entity.BaseEntity;
import life.genny.qwanda.entity.SearchEntity;
import life.genny.utils.VertxUtils;
import life.genny.utils.BaseEntityUtils;
import life.genny.models.GennyToken;
import org.kie.api.runtime.process.WorkflowProcessInstance;
import life.genny.utils.BaseEntityUtils;
import life.genny.qwandautils.GennySettings;

rule "SBE_APPLICATIONS"
    ruleflow-group 'GenerateSearches'
     no-loop true
    when
       not  SearchEntity (code == "SBE_APPLICATIONS")
        serviceToken : GennyToken( code == "PER_SERVICE")
     then
     	System.out.println("   Generate "+drools.getRule().getName() );

      SearchEntity searchBE = new SearchEntity(drools.getRule().getName(), "Applications")
                              .addSort("PRI_STAGE", "Status", SearchEntity.Sort.ASC)
                              .addFilter("PRI_CODE", SearchEntity.StringFilter.LIKE, "APP_%")
                              .addFilter("PRI_DISABLED", false)

                              .addColumn("PRI_TITLE", "Internship Title")
                              /*.addColumn("PRI_ASSOC_HC", "Host Company")*/
                              .addAssociatedColumn("LNK_INTERNSHIP", "PRI_NAME", "Host Company")
                              /*.addColumn("PRI_ADDRESS_FULL", "Address")*/
                              .addAssociatedColumn("LNK_INTERNSHIP", "PRI_ADDRESS_FULL", "Address")
                              .addColumn("PRI_STAGE", "Status")

                              /*.addColumn("PRI_ASSOC_INDUSTRY", "Industry")*/
                              .addAssociatedColumn("LNK_INDUSTRY", "PRI_NAME", "Industry")

                              /*.addColumn("PRI_ASSOC_OCCUPATION", "Occupation")*/
                              .addAssociatedColumn("LNK_OCCUPATION", "PRI_NAME", "Occupation")

                              .addColumn("PRI_START_DATE", "Start Date")
			                     .addColumn("PRI_ASSOC_DURATION", "Duration")

                              .addColumn("PRI_STATUS_COLOR", " ")
                              .addColumn("PRI_IMAGE_URL", " ")
                              .addColumn("PRI_IMAGE_SECONDARY", " ")

                              .addFilterableColumn("PRI_STATUS", "Status")
                              .addFilterableColumn("PRI_TITLE", "Internship Title")
                              .addFilterableColumn("PRI_ASSOC_INDUSTRY", "Industry")

                     			.setDisplayMode("row_data")

                              /* Actions */
                              .addAction("PRI_EVENT_VIEW_APPLICATION", "View Application")

                              .setPageStart(0).setPageSize(20);

      searchBE.setRealm(serviceToken.getRealm());

      insert(searchBE);
      VertxUtils.putObject(serviceToken.getRealm(), "", searchBE.getCode(), searchBE, serviceToken.getToken());

end
