package life.genny.rules;


import life.genny.qwanda.message.QCmdMessage;
import life.genny.qwanda.message.QBulkMessage;
import life.genny.qwanda.message.QDataBaseEntityMessage;
import life.genny.qwanda.message.QEventMessage;
import life.genny.rules.QRules;
import life.genny.qwandautils.JsonUtils;
import org.apache.logging.log4j.Logger;


import java.util.List;
import java.util.ArrayList;
import life.genny.qwanda.entity.BaseEntity;
import life.genny.qwanda.entity.SearchEntity;
import life.genny.utils.VertxUtils;
import life.genny.utils.BaseEntityUtils;
import life.genny.models.GennyToken;
import org.kie.api.runtime.process.WorkflowProcessInstance;
import life.genny.utils.BaseEntityUtils;
import life.genny.qwandautils.GennySettings;

rule "SBE_APPLICATIONS_APPLIED"
    ruleflow-group 'GenerateSearches'
     no-loop true
    when
       not  SearchEntity (code == "SBE_APPLICATIONS_APPLIED")
        serviceToken : GennyToken( code == "PER_SERVICE")
     then
     	System.out.println("   Generate "+drools.getRule().getName() );

      SearchEntity searchBE = new SearchEntity(drools.getRule().getName(), "My Applications")
                              .addSort("PRI_STATUS","Status",SearchEntity.Sort.ASC)
                              .addFilter("PRI_CODE", SearchEntity.StringFilter.LIKE, "APP_%")
                              .addFilter("PRI_DISABLED", false)
								 
                              .addColumn("PRI_IMAGE_SECONDARY", "Company Logo")
                              .addColumn("PRI_STATUS", "Status")
                              .addAssociatedColumn("LNK_INTERNSHIP", "PRI_NAME", "Internship Title")
                              .addAssociatedColumn("LNK_HOST_COMPANY", "PRI_NAME", "Host Company")
                              .addAssociatedColumn("LNK_INTERNSHIP", "PRI_ADDRESS_FULL", "Address")
                              
							  .addAssociatedColumn("LNK_INTERNSHIP", "LNK_INDUSTRY", "PRI_NAME", "Industry")
							  .addAssociatedColumn("LNK_INTERNSHIP", "LNK_OCCUPATION", "PRI_NAME", "Occupation")

                              .addColumn("PRI_START_DATE", "Start Date")
							  .addColumn("PRI_ASSOC_DURATION", "Duration")

							  .addFilterableColumn("PRI_STATUS", "Status")
							  .addFilterableColumn("PRI_TITLE", "Internship Title")
							  .addFilterableColumn("PRI_ASSOC_INDUSTRY", "Industry")

                              /* Actions */
                              .addAction("PRI_EVENT_VIEW_APPLICATION", "View Application")

                              .setPageStart(0).setPageSize(10);

      searchBE.setRealm(serviceToken.getRealm());

      insert(searchBE);
      VertxUtils.putObject(serviceToken.getRealm(), "", searchBE.getCode(), searchBE, serviceToken.getToken());

end
