package life.genny.rules;

import life.genny.qwanda.message.QDataAnswerMessage;
import life.genny.qwanda.message.QDataBaseEntityMessage;
import life.genny.models.GennyToken;
import life.genny.rules.QRules;
import life.genny.utils.BaseEntityUtils;
import life.genny.qwanda.Answer;
import life.genny.qwanda.Answers;
import io.vertx.core.json.JsonObject;
import org.json.JSONObject;
import java.util.Map;
import java.util.HashMap;
import life.genny.utils.VertxUtils;
import life.genny.utils.DropdownUtils;
import life.genny.qwanda.attribute.EntityAttribute;
import life.genny.qwanda.entity.BaseEntity;
import life.genny.qwanda.entity.EntityEntity;
import life.genny.qwanda.attribute.Attribute;
import life.genny.qwanda.attribute.AttributeLink;
import life.genny.qwandautils.JsonUtils;
import java.util.List;
import java.util.ArrayList;

rule "HELPER_PRI_NAME"
    ruleflow-group 'DataProcessing'
        salience 6000 
    when
	  userToken : GennyToken (code != "PER_SERVICE" )
	  serviceToken : GennyToken (code == "PER_SERVICE" )
	  answer : Answer( attributeCode == "PRI_FIRSTNAME" || attributeCode == "PRI_LASTNAME" )
	  answersToSave : Answers()
	  ruleDetails : RuleDetails()
	  output : OutputParam( )
	  beUtils : BaseEntityUtils( )

     then
 		System.out.println(drools.getRule().getName()+" - Rule fired! Processing Answer/Data : " + answer );

		BaseEntity userBe = beUtils.getBaseEntityByCode(answer.getTargetCode());
		System.out.println("userBe :: " + userBe);

		if (userBe != null) {

			String name = "";
			if (answer.getAttributeCode().equals("PRI_FIRSTNAME")) {

				name = answer.getValue();
				String lastName = userBe.getValue("PRI_LASTNAME", null);
				if (lastName != null) {
					name = name + " " + lastName;
				}

			} else if (answer.getAttributeCode().equals("PRI_LASTNAME")) {

				String firstName = userBe.getValue("PRI_FIRSTNAME", null);
				if (firstName != null) {
					name = firstName +  " " + answer.getValue();
				} else {
					name = answer.getValue();
				}
			}

			answersToSave.add(new Answer(userToken.getUserCode(), answer.getTargetCode(), "PRI_NAME", name, false, true));
			System.out.println("name :: " + name);
		}

		output.setTypeOfResult("NONE");
		output.setResultCode("NONE");  /* dont display anything new */
		update(output);

end