package life.genny.rules;

import life.genny.qwanda.message.QEventMessage;
import life.genny.models.GennyToken;
import life.genny.utils.BaseEntityUtils;
import life.genny.qwanda.Answer;
import life.genny.qwanda.entity.BaseEntity;
import life.genny.qwanda.message.QDataBaseEntityMessage;
import life.genny.utils.VertxUtils;
import life.genny.qwandautils.JsonUtils;
import life.genny.utils.TableUtils;

rule "SET_PRI_STATUS_AS_TRAINING"
    ruleflow-group 'Movement'
    no-loop true
    salience 1
    when
	 	userToken : GennyToken (code != "PER_SERVICE" )
		serviceToken : GennyToken (code == "PER_SERVICE" )
		associatedMenteeBe : BaseEntity()
		bucketCode : String(bucketCode.equals("ON_SHORE"))
		controlSignalCode : String(controlSignalCode.equals("TRAINING"))
    then
        System.out.println(drools.getRule().getName() + " : Rule fired");
 		BaseEntityUtils beUtils = new BaseEntityUtils(serviceToken, userToken);

		/* Refresh the BaseEntity because mysterious reasons Chris told me... he said, "Don’t ask me why. The rules suck" */
 		associatedMenteeBe = beUtils.getBaseEntityByCode(associatedMenteeBe.getCode());
		System.out.println("SET_PRI_STATUS_AS_MATCHED: associatedMenteeBe = " + associatedMenteeBe);

 		Answer answer = new Answer(userToken.getUserCode(),associatedMenteeBe.getCode(),"PRI_STATUS","TRAINING");
 		beUtils.saveAnswer(answer);

		System.out.println("SENDING MESSAGE TO FRONTEND");

		QDataBaseEntityMessage msg = new QDataBaseEntityMessage(associatedMenteeBe);
		msg.setToken(userToken.getToken());
		msg.setReplace(true);
		VertxUtils.writeMsg("webcmds", JsonUtils.toJson(msg));

		System.out.println("SET_PRI_STATUS_AS_TRAINING: Answer = " + answer);
		System.out.println("SET_PRI_STATUS_AS_TRAINING: associatedMenteeBe = " + associatedMenteeBe);

		TableUtils.moveEntity(associatedMenteeBe.getCode(), "SBE_ON_SHORE", "SBE_MENTEE_TRAINING", beUtils);

		         /* Sending toast message after mentee completes profile  */
                QCmdMessage toastMsg = new QCmdMessage("TOAST", "INFO");
                toastMsg.setMessage("Thanks for completing your training.");
                toastMsg.setToken(beUtils.getGennyToken().getToken());
                toastMsg.setSend(true);
                VertxUtils.writeMsg("webcmds", toastMsg);

                System.out.println("#### Sending email to mentee ####");

                QMessageGennyMSG verificationMsg = new QMessageGennyMSG.Builder("MSG_MENTEE_TRAINING_COMPLETED")
                    .addRecipient(associatedMenteeBe)
                    .addContext("BCC", "PRJ_MENTORMATCH")
                    .addContext("URL:ENCODE", "QUE_FAKE_PARENT/ACT_PRI_EVENT_SELECT_MENTOR")
                    .setUtils(beUtils)
                    .send();

                System.out.println("#### Sent email to mentee completing training ####");
         
		retract(associatedMenteeBe)
		retract(bucketCode)
		retract(controlSignalCode)

        System.out.println("End of " + drools.getRule().getName());
end
