package life.genny.rules;


import life.genny.qwanda.message.QCmdMessage;
import life.genny.qwanda.message.QBulkMessage;
import life.genny.qwanda.message.QDataBaseEntityMessage;
import life.genny.qwanda.message.QEventMessage;
import life.genny.rules.QRules;
import life.genny.qwandautils.JsonUtils;
import org.apache.logging.log4j.Logger;


import java.util.List;
import java.util.ArrayList;
import life.genny.qwanda.entity.BaseEntity;
import life.genny.qwanda.entity.SearchEntity;
import life.genny.utils.VertxUtils;
import life.genny.utils.BaseEntityUtils;
import life.genny.models.GennyToken;
import org.kie.api.runtime.process.WorkflowProcessInstance;
import life.genny.utils.BaseEntityUtils;
import life.genny.qwandautils.GennySettings;

rule "SBE_EPRS"
    ruleflow-group 'GenerateSearches'
     no-loop true
    when
       not  SearchEntity (code == "SBE_EPRS")
        serviceToken : GennyToken( code == "PER_SERVICE")
     then
     	System.out.println("   Generate "+drools.getRule().getName() );
     	BaseEntityUtils beUtils = new BaseEntityUtils(serviceToken);

		SearchEntity searchBE = new SearchEntity(drools.getRule().getName(), "Education Provider Representatives")
			/* Sorts */
			.addSort("PRI_NAME","Name",SearchEntity.Sort.ASC)
			/* .addSort("PRI_STATUS","Status",SearchEntity.Sort.ASC) */
			/* .addSort("PRI_ASSOC_EP","Education Provider",SearchEntity.Sort.ASC) */
			/* .addSort("PRI_JOB_TITLE","Job Title",SearchEntity.Sort.ASC) */
			/* .addSort("PRI_DEPARTMENT","Department",SearchEntity.Sort.ASC) */

			/* Filters */
			/* .addFilter("PRI_NAME",SearchEntity.StringFilter.LIKE, "%%")
			.addFilter("PRI_STATUS",SearchEntity.StringFilter.LIKE, "%%")
			.addFilter("PRI_ASSOC_EP",SearchEntity.StringFilter.LIKE, "%%")
			.addFilter("PRI_JOB_TITLE",SearchEntity.StringFilter.LIKE, "%%")
			.addFilter("PRI_DEPARTMENT",SearchEntity.StringFilter.LIKE, "%%") */
			.addFilter("PRI_CODE", SearchEntity.StringFilter.LIKE, "PER_%")
			.addFilter("PRI_IS_EDU_PRO_REP", true)

			/* Table Columns */
			.addColumn("PRI_IMAGE_URL", "Profile Picture")
			.addColumn("PRI_NAME", "Name")
			.addColumn("PRI_STATUS", "Status")
			.addColumn("PRI_ASSOC_EP", "Education Provider")
			.addColumn("PRI_EMAIL", "Email")
			.addColumn("PRI_MOBILE", "Mobile")
			.addColumn("PRI_JOB_TITLE", "Job Title")
			.addColumn("PRI_DEPARTMENT", "Department")
			.addColumn("PRI_LINKEDIN_URL", "LinkedIn")

			/* Filterable Columns */
			.addFilterableColumn("PRI_NAME", "Name")
			.addFilterableColumn("PRI_STATUS", "Status")
			.addFilterableColumn("PRI_ASSOC_EP", "Education Provider")

			/* Wildcard Whitelisted Attributes */
			.addWhitelist("PRI_NAME")

			/* Table actions */
			.addAction("PRI_EVENT_VIEW", "View Profile")
			.setPageStart(0).setPageSize(GennySettings.defaultPageSize);

		searchBE.setRealm(serviceToken.getRealm());
		insert(searchBE);
		VertxUtils.putObject(serviceToken.getRealm(), "", searchBE.getCode(), searchBE, serviceToken.getToken());

end
