package life.genny.rules;


import life.genny.qwanda.message.QCmdMessage;
import life.genny.qwanda.message.QBulkMessage;
import life.genny.qwanda.message.QDataBaseEntityMessage;
import life.genny.qwanda.message.QEventMessage;
import life.genny.rules.QRules;
import life.genny.qwandautils.JsonUtils;
import org.apache.logging.log4j.Logger;


import java.util.List;
import java.util.ArrayList;
import life.genny.qwanda.entity.BaseEntity;
import life.genny.qwanda.entity.SearchEntity;
import life.genny.utils.VertxUtils;
import life.genny.utils.BaseEntityUtils;
import life.genny.models.GennyToken;
import org.kie.api.runtime.process.WorkflowProcessInstance;
import life.genny.utils.BaseEntityUtils;
import life.genny.qwandautils.GennySettings;

rule "SBE_SUMMARY_INTERNS"
    ruleflow-group 'GenerateSearches'
     no-loop true
    when
       not  SearchEntity (code == "SBE_SUMMARY_INTERNS")
        serviceToken : GennyToken( code == "PER_SERVICE")
     then
     	System.out.println("   Generate "+drools.getRule().getName() );
     	BaseEntityUtils beUtils = new BaseEntityUtils(serviceToken);

		SearchEntity searchBE = new SearchEntity(drools.getRule().getName(), "Our Interns")
			/*
			.addSort("PRI_NAME","Name",SearchEntity.Sort.ASC)
			.addSort("PRI_STATUS","Status",SearchEntity.Sort.ASC)
			.addSort("PRI_NUM_JOURNALS","Journals",SearchEntity.Sort.DESC)
			.addSort("PRI_START_DATE","Start Date",SearchEntity.Sort.ASC)
			.addSort("PRI_ASSOC_EP","EP",SearchEntity.Sort.ASC)
			.addSort("PRI_ADDRESS_STATE", "State",SearchEntity.Sort.ASC)
			*/
			.addFilter("PRI_CODE", SearchEntity.StringFilter.LIKE, "PER_%")
			.addFilter("PRI_IS_INTERN", true)
			.addFilter("PRI_DISABLED", false)
			
			.addCombinedSearch("SBE_COUNT_PLACED_INTERNS", "Placed Interns")
			.addCombinedSearch("SBE_COUNT_PROGRESS_INTERNS", "In Progress Interns")
			
			/* Table Columns */
			.addColumn("PRI_STATUS", "Status")
			.addColumn("PRI_NAME", "Name")
			.addColumn("PRI_EMAIL", "Email")
			.addColumn("PRI_MOBILE", "Mobie")
			.addColumn("PRI_STUDENT_ID", "Student Id")
			.addColumn("PRI_ASSOC_INDUSTRY", "Industry")
			.addColumn("PRI_ASSOC_OCCUPATION", "Specialisation")
			.addColumn("PRI_IMAGE_URL", " ")
			
			/* Actions */
			.addSearchAction("PRI_EVENT_QUE_TREE_ITEM_INTERNS", "View")
			.addSearchAction("PRI_EVENT_QUE_TAB_BUCKET_VIEW", "Track")

			/* Display Mode */
			.setDisplayMode("our_interns")
			.setPageStart(0).setPageSize(GennySettings.defaultPageSize);

		searchBE.setRealm(serviceToken.getRealm());
		insert(searchBE);
		VertxUtils.putObject(serviceToken.getRealm(), "", searchBE.getCode(), searchBE, serviceToken.getToken());

end
