package life.genny.rules;


import life.genny.qwanda.message.QCmdMessage;
import life.genny.qwanda.message.QBulkMessage;
import life.genny.qwanda.message.QDataBaseEntityMessage;
import life.genny.qwanda.message.QEventMessage;
import life.genny.rules.QRules;
import life.genny.qwandautils.JsonUtils;
import org.apache.logging.log4j.Logger;


import java.util.List;
import java.util.ArrayList;
import life.genny.qwanda.entity.BaseEntity;
import life.genny.qwanda.entity.SearchEntity;
import life.genny.utils.VertxUtils;
import life.genny.utils.BaseEntityUtils;
import life.genny.models.GennyToken;
import org.kie.api.runtime.process.WorkflowProcessInstance;
import life.genny.utils.BaseEntityUtils;
import life.genny.qwandautils.GennySettings;

rule "SBE_HOST_COMPANIES"
    ruleflow-group 'GenerateSearches'
     no-loop true
    when
       not  SearchEntity (code == "SBE_HOST_COMPANIES")
        serviceToken : GennyToken( code == "PER_SERVICE")
     then
     	System.out.println("   Generate "+drools.getRule().getName() );
     	BaseEntityUtils beUtils = new BaseEntityUtils(serviceToken);

		SearchEntity searchBE = new SearchEntity(drools.getRule().getName(), "Host Companies")
			/* Sorts */
			.addSort("PRI_NAME", "Name", SearchEntity.Sort.ASC)
			.addSort("PRI_CREATED_DATE", "Date Created", SearchEntity.Sort.DESC)
			/* .addSort("PRI_ASSOC_INDUSTRY", "Company Industry", SearchEntity.Sort.ASC) */
			/* .addSort("PRI_ADDRESS_STATE", "State", SearchEntity.Sort.ASC) */
			/* .addSort("PRI_VALIDATION", "Validation", SearchEntity.Sort.ASC) */
			/* .addSort("PRI_STATUS", "Status", SearchEntity.Sort.ASC) */
			
			/* Filters */
			.addFilter("PRI_CODE", SearchEntity.StringFilter.LIKE, "CPY_%")
			.addFilter("PRI_IS_HOST_CPY", true)
			.addFilter("PRI_STATUS", SearchEntity.StringFilter.EQUAL, "ACTIVE")
			
			/* Table Columns */
			.addColumn("PRI_IMAGE_URL", "Logo")
			.addColumn("PRI_NAME", "Name")
			.addColumn("PRI_CREATED_DATE", "Date Created")
			.addColumn("PRI_STATUS", "Status")
			.addColumn("PRI_VALIDATION", "Validation")
			.addColumn("PRI_MOBILE", "Phone")
			.addColumn("PRI_ADDRESS_FULL","Address")
			.addColumn("PRI_ADDRESS_STATE","State")
			.addColumn("PRI_ADDRESS_COUNTRY","Country")

			/* Filterable Columns */
			.addFilterableColumn("PRI_NAME", "Name")
			.addFilterableColumn("PRI_ASSOC_INDUSTRY", "Company Industry")
			.addFilterableColumn("PRI_ADDRESS_STATE", "State")
			.addFilterableColumn("PRI_VALIDATION", "Validation")
			.addFilterableColumn("PRI_STATUS", "Status")
			.addFilterableColumn("PRI_CREATED_DATE", "Date Created")

			/* Wildcard Whitelisted Attributes */
			.addWhitelist("PRI_NAME")

			/* Table actions */
			.addAction("PRI_EVENT_VIEW", "View Profile")
			.setPageStart(0).setPageSize(GennySettings.defaultPageSize);

		searchBE.setRealm(serviceToken.getRealm());
		insert(searchBE);
		VertxUtils.putObject(serviceToken.getRealm(), "", searchBE.getCode(), searchBE, serviceToken.getToken());

end
