package life.genny.rules;


import life.genny.qwanda.message.QCmdMessage;
import life.genny.qwanda.message.QBulkMessage;
import life.genny.qwanda.message.QDataBaseEntityMessage;
import life.genny.qwanda.message.QEventMessage;
import life.genny.rules.QRules;
import life.genny.qwandautils.JsonUtils;
import org.apache.logging.log4j.Logger;


import java.util.List;
import java.util.ArrayList;
import life.genny.qwanda.entity.BaseEntity;
import life.genny.qwanda.entity.SearchEntity;
import life.genny.utils.VertxUtils;
import life.genny.utils.BaseEntityUtils;
import life.genny.models.GennyToken;
import org.kie.api.runtime.process.WorkflowProcessInstance;
import life.genny.utils.BaseEntityUtils;
import life.genny.qwandautils.GennySettings;

rule "SBE_INTERNSHIPS"
	ruleflow-group 'GenerateSearches'
	no-loop true
	when
		not  SearchEntity (code == "SBE_INTERNSHIPS")
		serviceToken : GennyToken( code == "PER_SERVICE")
	then
		System.out.println("   Generate "+drools.getRule().getName() );
		BaseEntityUtils beUtils = new BaseEntityUtils(serviceToken);

		SearchEntity searchBE = new SearchEntity(drools.getRule().getName(), "Internships")
			/* Sorts */
			.addSort("PRI_CREATED", "Date Created", SearchEntity.Sort.DESC)
			.addSort("PRI_STATUS","Status",SearchEntity.Sort.ASC) 
			/* .addSort("PRI_ASSOC_INDUSTRY","Industry",SearchEntity.Sort.ASC) */
			/* .addSort("PRI_ASSOC_HC","Host Company",SearchEntity.Sort.ASC) */
			/* .addSort("PRI_INTERNSHIP_START_DATE","Start Date",SearchEntity.Sort.ASC) */

			/* Filters */
			.addFilter("PRI_IS_INTERNSHIP", true)
			.addFilter("PRI_CODE", SearchEntity.StringFilter.LIKE, "BEG_%")
			/*.addFilter("PRI_STATUS", SearchEntity.StringFilter.LIKE, "ACTIVE")*/
			/* Table Columns */
			.addColumn("PRI_IMAGE_URL", "Company Logo")
			.addColumn("PRI_NAME", "Title")
			/*.addColumn("PRI_INTERNSHIP_TITLE", "Title")*/
			.addColumn("PRI_CREATED", "Date Created")
			.addColumn("PRI_STATUS", "Status")
			/* .addColumn("PRI_ASSOC_HC", "Host Company") */
			.addAssociatedColumn("LNK_HOST_COMPANY", "PRI_NAME", "Host Company")
			.addColumn("PRI_ADDRESS_FULL", "Address")
			.addColumn("PRI_ADDRESS_STATE", "State")
			.addColumn("PRI_ADDRESS_COUNTRY", "Country")
			.addColumn("PRI_INTERNSHIP_START_DATE", "Proposed Start Date")
			.addColumn("PRI_ASSOC_INDUSTRY", "Industry")
			.addColumn("PRI_NO_OF_INTERNS", "Number of allowed Interns")
			.addAssociatedColumn("LNK_SOFTWARE", "PRI_NAME", "Software")
			.addAssociatedColumn("LNK_WORKSITE_SELECT", "PRI_NAME", "Worksite")
			.addColumn("PRI_ASSOC_OCCUPATION", "Specialisation")

			/* Filterable Columns */
			.addFilterableColumn("PRI_NAME", "Title")
			.addFilterableColumn("PRI_STATUS", "Status")
			.addFilterableColumn("PRI_ASSOC_INDUSTRY", "Industry")
			.addFilterableColumn("PRI_ASSOC_HC", "Host Company")
			.addFilterableColumn("PRI_ADDRESS_STATE", "State")
			.addFilterableColumn("PRI_ADDRESS_COUNTRY", "Country")
			.addFilterableColumn("PRI_CREATED_DATE", "Date Created")

			/* Wildcard blacklist */
			/* .addBlacklist("PRI_ROLES_AND_RESPONSIBILITIES") */
			/* .addBlacklist("PRI_BASE_LEARNING_OUTCOMES") */

			/* Wildcard Whitelisted Attributes */
			.addWhitelist("PRI_NAME")
			/* .addWhitelist("PRI_ASSOC_HC") */
			.setWildcardDepth(1)

			/* Row Actions */
			.addAction("PRI_EVENT_VIEW", "View")

			/* Table Actions */
			.addSearchAction("PRI_EVENT_MAP_VIEW", "Map View")

			.setPageStart(0).setPageSize(30);

		searchBE.setRealm(serviceToken.getRealm());
		insert(searchBE);
		VertxUtils.putObject(serviceToken.getRealm(), "", searchBE.getCode(), searchBE, serviceToken.getToken());

end
