
   
package life.genny.rules;

import life.genny.qwanda.message.QEventMessage;
import life.genny.models.GennyToken;
import life.genny.utils.VertxUtils;
import io.vertx.core.json.JsonObject;
import life.genny.qwanda.utils.OutputParam;
import org.apache.commons.lang3.StringUtils;
import life.genny.qwanda.message.QCmdMessage;
import life.genny.utils.VertxUtils;
import life.genny.utils.BaseEntityUtils;
import life.genny.qwanda.message.MessageData;
import life.genny.utils.TableUtils;


rule "MENTOR_TABLE_VIEW"
    ruleflow-group 'EventProcessing'
		salience 2
    no-loop
    when
		$message : QEventMessage(data.code matches "SCH_ACT_PRI_EVENT_QUE_TREE_ITEM_MENTORS")
		userToken : GennyToken (code != "PER_SERVICE" )
		serviceToken : GennyToken (code == "PER_SERVICE" )
 		output: OutputParam()
    then
		System.out.println(drools.getRule().getName() + " - Rule fired");
        BaseEntityUtils beUtils = new BaseEntityUtils(serviceToken, userToken);
        TableUtils.searchTable(beUtils,"SBE_MENTORS", true);
        output.setTypeOfResult("NONE");
        output.setResultCode("NONE");  /* dont display anything new */
		retract( $message);
	end