package life.genny.rules;
import life.genny.qwanda.message.QDataAnswerMessage;
import life.genny.models.GennyToken;
import life.genny.rules.QRules;
import life.genny.utils.BaseEntityUtils;
import life.genny.qwanda.Answer;
import life.genny.qwanda.entity.BaseEntity;
import life.genny.utils.OutputParam;
import life.genny.qwandautils.KeycloakUtils;
import java.util.UUID;

import java.util.List;
import java.util.ArrayList;

rule "SEND_PLACEHOLDER_ASKS"
    ruleflow-group 'ScenarioSetup'
    no-loop true
    salience 5
    when
	 	userToken : GennyToken (code != "PER_SERVICE" )
		serviceToken : GennyToken (code == "PER_SERVICE" )
		not tempTrigger : String(tempTrigger matches "DONT_SEND_ASKS")
		output : OutputParam()

     then
		System.out.println(drools.getRule().getName() + ": Rule fired");
 		
 		BaseEntityUtils beUtils = new BaseEntityUtils(userToken);


		/* Save Some Info for Buckets */
		beUtils.saveAnswer(new Answer(userToken.getUserCode(), userToken.getUserCode(), "PRI_STATUS", "PROGRESS"));

		/* SEND TEMPLATE ASKS */
		QwandaMessage askGrp = QuestionUtils.getQuestions(userToken.getUserCode(), userToken.getUserCode(), "QUE_UNITY_GRP", serviceToken.getToken());
		Ask unityAskGrp = askGrp.asks.getItems()[0];

		QDataAskMessage askMsg = new QDataAskMessage(unityAskGrp);

		askMsg.setToken(userToken.getToken());
		String sendingMsg = JsonUtils.toJson(askMsg);
		Integer length = sendingMsg.length();

		System.out.println(drools.getRule().getName()  + " - Sending placheolder ask grp");

		VertxUtils.writeMsg("webcmds", sendingMsg);
			
end