package life.genny.rules;


import life.genny.qwanda.message.QCmdMessage;
import life.genny.qwanda.message.QBulkMessage;
import life.genny.qwanda.message.QDataBaseEntityMessage;
import life.genny.qwanda.message.QEventMessage;
import life.genny.rules.QRules;
import life.genny.qwandautils.JsonUtils;
import org.apache.logging.log4j.Logger;
import java.util.List;
import java.util.ArrayList;
import life.genny.qwanda.entity.BaseEntity;
import life.genny.qwanda.entity.SearchEntity;
import life.genny.utils.VertxUtils;
import life.genny.utils.BaseEntityUtils;
import life.genny.models.GennyToken;
import org.kie.api.runtime.process.WorkflowProcessInstance;
import life.genny.utils.BaseEntityUtils;
import life.genny.qwandautils.GennySettings;

rule "SBE_COUNTS_EDU_PRO_REP"
   ruleflow-group 'GenerateSearches'
   no-loop true
   when
      not  SearchEntity (code == "SBE_COUNTS_EDU_PRO_REP")
      serviceToken : GennyToken( code == "PER_SERVICE")
   then
     	System.out.println("   Generate "+drools.getRule().getName() );

      SearchEntity searchBE = new SearchEntity(drools.getRule().getName(), "Student Data")
							  .addFilter("PRI_CODE", SearchEntity.StringFilter.LIKE, "DUMMY")

							  .addLinkedSearch("CNS_SBE_COUNT_TOTAL_INTERNS", "Total Interns")
							  .addLinkedSearch("CNS_SBE_COUNT_AVAILABLE_INTERNS", "Available Interns")
							  .addLinkedSearch("CNS_SBE_COUNT_SHORTLISTED_INTERNS", "Shortlisted Interns")
							  .addLinkedSearch("CNS_SBE_COUNT_INTERVIEWED_INTERNS", "Interviewing  Interns")
							  .addLinkedSearch("CNS_SBE_COUNT_OFFERED_INTERNS", "Offered Interns")
							  .addLinkedSearch("CNS_SBE_COUNT_PLACED_INTERNS", "Placed Interns")
							  .addLinkedSearch("CNS_SBE_COUNT_PROGRESS_INTERNS", "In Progress Interns")
                              
                              /* Display Mode */
                              .setDisplayMode("nested_summary_pane")
                              .setPageStart(0).setPageSize(1);

      searchBE.setRealm(serviceToken.getRealm());

      insert(searchBE);
      VertxUtils.putObject(serviceToken.getRealm(), "", searchBE.getCode(), searchBE, serviceToken.getToken());

end
