package life.genny.rules;


import life.genny.qwanda.message.QCmdMessage;
import life.genny.qwanda.message.QBulkMessage;
import life.genny.qwanda.message.QDataBaseEntityMessage;
import life.genny.qwanda.message.QEventMessage;
import life.genny.rules.QRules;
import life.genny.qwandautils.JsonUtils;
import org.apache.logging.log4j.Logger;
import java.util.List;
import java.util.ArrayList;
import life.genny.qwanda.entity.BaseEntity;
import life.genny.qwanda.entity.SearchEntity;
import life.genny.utils.VertxUtils;
import life.genny.utils.BaseEntityUtils;
import life.genny.models.GennyToken;
import org.kie.api.runtime.process.WorkflowProcessInstance;
import life.genny.utils.BaseEntityUtils;
import life.genny.qwandautils.GennySettings;

rule "SBE_SUMMARY_INPROGRESS_APPLICATION"
   ruleflow-group 'GenerateSearches'
   no-loop true
   when
      not  SearchEntity (code == "SBE_SUMMARY_INPROGRESS_APPLICATION")
      serviceToken : GennyToken( code == "PER_SERVICE")
   then
     	System.out.println("   Generate "+drools.getRule().getName() );

      SearchEntity searchBE = new SearchEntity(drools.getRule().getName(), "My Internship")
                              .addSort("PRI_CREATED", "Created", SearchEntity.Sort.DESC)

                              .addFilter("PRI_CODE", SearchEntity.StringFilter.LIKE, "APP_%")
                              .addFilter("PRI_STATUS", SearchEntity.StringFilter.EQUAL, "PROGRESS")
                              .addFilter("PRI_DISABLED", false)

                              /* Columns */
                              .addColumn("PRI_TITLE", "Internship")
                              .addColumn("PRI_ASSOC_HC", "Host Company")
                              .addColumn("PRI_ROLES_AND_RESPONSIBILITIES", "Roles and Responsibilities")
                              .addColumn("PRI_BASE_LEARNING_OUTCOMES", "Learning Outcomes")
                              .addColumn("PRI_SPECIFIC_LEARNING_OUTCOMES", "Specific Learning Outcomes")
                              .addColumn("PRI_START_DATE", "Internship Start Date")
                              .addColumn("PRI_END_DATE", "Internship End Date")
                              .addColumn("PRI_ASSOC_DURATION", "Internship Duration")
                              .addColumn("PRI_DAYS_PER_WEEK", "Number of Days per week")
                              .addColumn("PRI_PROGRESS", "Application Progress")

                              /* Nested Search */

                              /* Actions */
                              .addDefaultAction("PRI_EVENT_VIEW_APPLICATION", "View")
                              
                              /* Display Mode */
                              .setDisplayMode("my_internship")
                              .setPageStart(0).setPageSize(5);

      searchBE.setRealm(serviceToken.getRealm());

      insert(searchBE);
      VertxUtils.putObject(serviceToken.getRealm(), "", searchBE.getCode(), searchBE, serviceToken.getToken());

end
