package life.genny.rules;


import life.genny.qwanda.message.QCmdMessage;
import life.genny.qwanda.message.QBulkMessage;
import life.genny.qwanda.message.QDataBaseEntityMessage;
import life.genny.qwanda.message.QEventMessage;
import life.genny.rules.QRules;
import life.genny.qwandautils.JsonUtils;
import org.apache.logging.log4j.Logger;
import java.util.List;
import java.util.ArrayList;
import life.genny.qwanda.entity.BaseEntity;
import life.genny.qwanda.entity.SearchEntity;
import life.genny.utils.VertxUtils;
import life.genny.utils.BaseEntityUtils;
import life.genny.models.GennyToken;
import org.kie.api.runtime.process.WorkflowProcessInstance;
import life.genny.utils.BaseEntityUtils;
import life.genny.qwandautils.GennySettings;

rule "SBE_SUMMARY_MY_APPLICATIONS"
   ruleflow-group 'GenerateSearches'
   no-loop true
   when
      not  SearchEntity (code == "SBE_SUMMARY_MY_APPLICATIONS")
      serviceToken : GennyToken( code == "PER_SERVICE")
   then
     	System.out.println("   Generate "+drools.getRule().getName() );

      SearchEntity searchBE = new SearchEntity(drools.getRule().getName(), "Applications")
                              .addSort("PRI_STATUS", "Created", SearchEntity.Sort.DESC)

                              .addFilter("PRI_CODE", SearchEntity.StringFilter.LIKE, "APP_%")
                              .addFilter("PRI_STATUS", SearchEntity.StringFilter.LIKE, "%")
                              .addFilter("PRI_DISABLED", false)

                              /* Columns */
                              .addColumn("PRI_TITLE", "Internship")
                              .addColumn("PRI_ASSOC_HC", "Host Company")
                              .addColumn("PRI_STATUS", "Status")

                              /* Actions */
                              .addSearchAction("PRI_EVENT_QUE_TREE_ITEM_APPLICATIONS_APPLIED", "View")
                              
                              /* Display Mode */
                              .setDisplayMode("dashboard_search")
                              .setPageStart(0).setPageSize(5);

      searchBE.setRealm(serviceToken.getRealm());

      insert(searchBE);
      VertxUtils.putObject(serviceToken.getRealm(), "", searchBE.getCode(), searchBE, serviceToken.getToken());

end
