package life.genny.rules;

import life.genny.qwanda.message.QCmdMessage;
import life.genny.qwanda.message.QBulkMessage;
import life.genny.qwanda.message.QDataBaseEntityMessage;
import life.genny.qwanda.message.QEventMessage;
import life.genny.rules.QRules;
import life.genny.qwandautils.JsonUtils;
import org.apache.logging.log4j.Logger;


import java.util.List;
import java.util.ArrayList;
import life.genny.qwanda.entity.BaseEntity;
import life.genny.qwanda.entity.SearchEntity;
import life.genny.utils.VertxUtils;
import life.genny.utils.BaseEntityUtils;
import life.genny.models.GennyToken;
import org.kie.api.runtime.process.WorkflowProcessInstance;
import life.genny.utils.BaseEntityUtils;
import life.genny.qwandautils.GennySettings;

rule "SBE_BUCKET_SCENARIO_FIVE"
    ruleflow-group 'GenerateSearches'
     no-loop true
    when
       not  SearchEntity (code == "SBE_BUCKET_SCENARIO_FIVE")
        serviceToken : GennyToken( code == "PER_SERVICE")
     then
     	System.out.println("   Generate "+drools.getRule().getName() );

      SearchEntity searchBE = new SearchEntity(drools.getRule().getName(), "Scenario 5")
                              .addSort("PRI_CURRENT_QUESTION", "Question", SearchEntity.Sort.ASC)
                              .addFilter("PRI_CODE", SearchEntity.StringFilter.LIKE, "PER_%")
                              .addFilter("PRI_IS_STUDENT", true)
                              .addFilter("PRI_CURRENT_SCENARIO", SearchEntity.Filter.EQUALS, 5)
                              .addFilter("PRI_STATUS", SearchEntity.StringFilter.EQUAL, "PROGRESS")
								 
                              .addColumn("PRI_NAME", "Name")
                              .addColumn("PRI_EMAIL", "Email")

                              .addColumn("PRI_CURRENT_PART", "Part")
                              .addColumn("PRI_CURRENT_QUESTION", "Question")

                              .addColumn("PRI_IMAGE_URL", " ")
                              .addColumn("PRI_STATUS_COLOR", " ")
                              /* Actions */
                              .addAction("PRI_EVENT_VIEW", "View Profile")

                              .setDisplayMode("CARDS:SCENARIOS")

                              .addGroupBy("PRI_CURRENT_PART")
                              
                              .setPageStart(0).setPageSize(1000);

      searchBE.setRealm(serviceToken.getRealm());

      insert(searchBE);
      VertxUtils.putObject(serviceToken.getRealm(), "", searchBE.getCode(), searchBE, serviceToken.getToken());

end
