package life.genny.rules;
import life.genny.models.GennyToken;
import life.genny.rules.QRules;
import life.genny.utils.BaseEntityUtils;
import life.genny.qwanda.Answer;
import life.genny.qwanda.entity.BaseEntity;
import life.genny.qwanda.utils.OutputParam;
import life.genny.utils.TaskUtils;
import java.util.List;
import java.util.ArrayList;
import life.genny.utils.QuestionUtils;

rule "LNK_SPECIFY_HOST_CPY"
	ruleflow-group 'DataProcessing'
	salience 500
	no-loop true
	when
		userToken : GennyToken (code != "PER_SERVICE" )
		serviceToken : GennyToken (code == "PER_SERVICE" )
		answer : Answer( attributeCode == "LNK_SPECIFY_HOST_CPY" && ( targetCode.startsWith("PER_") ) )
		output : OutputParam()
		beUtils : BaseEntityUtils()

	then
		System.out.println(drools.getRule().getName()+": Rule fired");
 		
		/* Get Target User BE */
 		String targetCode = answer.getTargetCode();
 		System.out.println("targetCode = " + targetCode); 
 		String value = answer.getValue();
 		System.out.println("value = " + value); 

		boolean enabled = true;
		if (value.equals("SEL_NO")) {
			enabled = false;
		}

		QDataAskMessage askMsg = QuestionUtils.getAsks(userToken.getUserCode(), targetCode, "QUE_QA_HOST_CPY_REP_GRP", userToken.getToken());

		if (askMsg != null) {
			/* SET REPLACE TRUE */
			for (Ask ask : askMsg.getItems()[0].getChildAsks()) {
				if (ask.getQuestionCode().equals("QUE_SELECT_HOST_COMPANY")) {
					/* Disable and send the ask */
					System.out.println("Setting HC Dropdown to enabled = " + enabled);
					TaskUtils.enableTaskQuestion(ask, enabled, userToken);
				}
			}
		} else {
			System.out.println("Could not fetch ask from cache: QUE_QA_HOST_CPY_REP_GRP"); 
		}

		output.setTypeOfResult("NONE");
		output.setResultCode("NONE");
end
