package life.genny.rules;
import life.genny.models.GennyToken;
import life.genny.rules.QRules;
import life.genny.utils.BaseEntityUtils;
import life.genny.qwanda.Answer;
import life.genny.qwanda.entity.BaseEntity;
import life.genny.qwanda.utils.OutputParam;
import life.genny.utils.TaskUtils;
import java.util.List;
import java.util.ArrayList;
import life.genny.utils.QuestionUtils;

rule "LNK_SPECIFY_ABN"
	ruleflow-group 'DataProcessing'
	salience 500
	no-loop true
	when
		userToken : GennyToken (code != "PER_SERVICE" )
		serviceToken : GennyToken (code == "PER_SERVICE" )
		answer : Answer( attributeCode == "LNK_SPECIFY_ABN" && ( targetCode.startsWith("CPY_") ) )
		output : OutputParam()
		beUtils : BaseEntityUtils()

	then
		System.out.println(drools.getRule().getName()+": Rule fired");

		/* Get Target User BE */
 		String targetCode = answer.getTargetCode();
 		System.out.println("targetCode = " + targetCode);
 		String value = answer.getValue();
 		System.out.println("value = " + value);

		boolean enabled = true;

		if (beUtils.cleanUpAttributeValue(value).equals("SEL_NO")) {
			enabled = false;
			beUtils.saveAnswer(new Answer(userToken.getUserCode(), targetCode, "PRI_ABN", ""));
		}

		/* QDataAskMessage askMsg = QuestionUtils.getAsks(userToken.getUserCode(), targetCode, "QUE_HOST_CPY_GRP", userToken.getToken()); */

		QDataAskMessage askMsg = QuestionUtils.getAsks("PER_SOURCE", "PER_TARGET", "QUE_HOST_CPY_GRP", beUtils.getGennyToken().getToken());

		if (askMsg == null) {
			log.error("AskMessage is null for QUE_HOST_CPY_GRP");
		}

		String json = JsonUtils.toJson(askMsg);
		json = json.replaceAll("PER_SOURCE", userToken.getUserCode());
		json = json.replaceAll("PER_TARGET", targetCode);

		askMsg = JsonUtils.fromJson(json, QDataAskMessage.class);

		if (askMsg != null) {
			/* SET REPLACE TRUE */
			for (Ask ask : askMsg.getItems()[0].getChildAsks()) {
				if (ask.getQuestionCode().equals("QUE_COMPANY_ABN")) {
					/* Disable and send the ask */
					System.out.println("Setting ABN field to enabled = " + enabled);
					TaskUtils.enableTaskQuestion(ask, enabled, userToken);
				}
			}
		} else {
			System.out.println("Could not fetch ask from cache: QUE_QA_HOST_CPY_REP_GRP");
		}

		output.setTypeOfResult("NONE");
		output.setResultCode("NONE");
end
