package life.genny.rules;
import life.genny.models.GennyToken;
import life.genny.rules.QRules;
import life.genny.utils.BaseEntityUtils;
import life.genny.qwanda.Answer;
import life.genny.qwanda.entity.BaseEntity;
import life.genny.qwanda.utils.OutputParam;
import java.util.List;
import java.util.ArrayList;

rule "PRI_STAR_RATING"
	ruleflow-group 'DataProcessing'
	salience 500
	no-loop true
	when
		userToken : GennyToken (code != "PER_SERVICE" )
		serviceToken : GennyToken (code == "PER_SERVICE" )
		answer : Answer( attributeCode == "PRI_STAR_RATING" && ( targetCode.startsWith("PER_") ) )
		output : OutputParam()
		beUtils : BaseEntityUtils()

	then
		System.out.println(drools.getRule().getName()+": Rule fired");
 		
		/* Get Target User BE */
 		String targetCode = answer.getTargetCode();
 		System.out.println("targetCode = " + targetCode); 
 		Double value = Double.valueOf(answer.getValue());
 		System.out.println("value = " + value); 
 		
		/* Get all their applications */
		SearchEntity searchBE = new SearchEntity("SBE_APPS_FOR_USER", "Applications for user")
			.addFilter("PRI_CODE", SearchEntity.StringFilter.LIKE, "APP_%")
			.addFilter("PRI_INTERN_CODE", SearchEntity.StringFilter.EQUAL, targetCode)
			.setPageStart(0).setPageSize(1000000);
 		
		searchBE.setRealm(userToken.getRealm());
		List<BaseEntity> applications = beUtils.getBaseEntitys(searchBE);

		/* Save Star Rating for each APP */
		for (BaseEntity app : applications) {
			System.out.println("Saving Star Rating for " + app.getCode());
			beUtils.saveAnswer(new Answer(userToken.getUserCode(), app.getCode(), "PRI_STAR_RATING", value));
		}

		output.setTypeOfResult("NONE");
		output.setResultCode("NONE");
end
