package life.genny.gadaq.inference;

import life.genny.qwandaq.message.QDataAnswerMessage;
import life.genny.qwandaq.utils.KafkaUtils;
import life.genny.qwandaq.models.UserToken;
import life.genny.kogito.common.utils.KogitoUtils;

ruleflow-group 'Inference'

rule InferName 
when
	answer: Answer()
	userToken: UserToken()
	kogitoUtils : KogitoUtils()
then
	String sourceCode = answer.getSourceCode();
	String targetCode = answer.getTargetCode();
	String attributeCode = answer.getAttributeCode();
	String value = answer.getValue();

	System.out.println("Inferring GENNYQ! Source Code: " + sourceCode + " Target Code: " + targetCode + " Attribute Code: " + attributeCode + " Value: " + value);
end
