package life.genny.gadaq.inference;

import life.genny.qwandaq.message.QDataAnswerMessage;
import life.genny.qwandaq.Answer;
import life.genny.qwandaq.utils.KafkaUtils;
import life.genny.qwandaq.models.UserToken;
import life.genny.kogito.common.utils.KogitoUtils;
import org.apache.commons.lang3.text.WordUtils;
import org.apache.commons.lang3.StringUtils;

ruleflow-group 'Inference'

rule InitialsInference 
	ruleflow-group 'DataProcessing'
	salience 10000 
	no-loop
when
	answer: Answer( attributeCode == "PRI_FIRSTNAME" )
	userToken: UserToken()
	kogitoUtils : KogitoUtils()
then
	String sourceCode = answer.getSourceCode();
	String targetCode = answer.getTargetCode();
	String attributeCode = answer.getAttributeCode();
	String firstname =answer.getValue();

	System.out.println(drools.getRule().getName()+ ":" + sourceCode + " Target Code: " + targetCode + " Attribute Code: " + attributeCode + " Value: " + firstname);

		/*BaseEntity person = beUtils.getBaseEntityByCode(targetCode);*/
		
		/* Parse json answer and save the individual answers */

		firstname = firstname.toLowerCase().trim();
		firstname = WordUtils.capitalize(firstname);

		System.out.println(drools.getRule().getName()+": Firstname:"+firstname);

end
