package life.genny.rules;


rule "SBE_CUSTOMERS"
    ruleflow-group 'GenerateSearches'
     no-loop true
    when
       not  SearchEntity (code == "SBE_CUSTOMERS")
        serviceToken : GennyToken( code == "PER_SERVICE")
     then
     	System.out.println("   Generate "+drools.getRule().getName());

      SearchEntity searchBE = new SearchEntity(drools.getRule().getName(), "Applications")
							  /* Sorts */
                              .addSort("PRI_NAME", "Name", SearchEntity.Sort.ASC)

							  /* Filters */
                              .addFilter("PRI_CODE", SearchEntity.StringFilter.LIKE, "PER_%")

							  /* Columns */
                              .addColumn("PRI_NAME", "Name")

                              .setPageStart(0).setPageSize(20);

      searchBE.setRealm(serviceToken.getRealm());

      insert(searchBE);
      VertxUtils.putObject(serviceToken.getRealm(), "", searchBE.getCode(), searchBE, serviceToken.getToken());

end