package life.genny.rules;


rule "SBE_PROPERTIES"
    ruleflow-group 'GenerateSearches'
     no-loop true
    when
       not  SearchEntity (code == "SBE_PROPERTIES")
        serviceToken : GennyToken( code == "PER_SERVICE")
     then
		System.out.println("   Generate "+drools.getRule().getName() );

      SearchEntity searchBE = new SearchEntity(drools.getRule().getName(), "Properties")
							  /* Sorts */
                              .addSort("PRI_NAME", "Name", SearchEntity.Sort.ASC)

							  /* Filters */
                              .addFilter("PRI_CODE", SearchEntity.StringFilter.LIKE, "PRP_%")
                              /* .addFilter("PRI_IS_BUILDING", true) */
                              
							  /* Columns */
                              .addColumn("PRI_NAME", "Name")
                              .addColumn("PRI_HAS_INTERCOM", "Intercom")
                              .addAssociatedColumn("LNK_AREA_UNIT", "PRI_NAME", "Area Unit")
                              .setPageStart(0).setPageSize(20);

      searchBE.setRealm(serviceToken.getRealm());

      insert(searchBE);
      VertxUtils.putObject(serviceToken.getRealm(), "", searchBE.getCode(), searchBE, serviceToken.getToken());

end