package life.genny.rules;

import java.io.IOException;

global life.genny.qwanda.message.QBulkMessage payload;

import life.genny.qwanda.message.QDataAnswerMessage;
import life.genny.models.GennyToken;
import life.genny.rules.QRules;
import life.genny.utils.BaseEntityUtils;
import life.genny.utils.CapabilityUtils;
import life.genny.qwanda.Answer;
import java.util.List;
import java.util.ArrayList;
import life.genny.model.OutputParamTreeSet;
import life.genny.qwanda.entity.BaseEntity;
import life.genny.qwanda.message.QDataBaseEntityMessage;
import life.genny.qwanda.message.QBulkMessage;
import life.genny.utils.TableUtils;
import life.genny.qwanda.entity.SearchEntity;
import life.genny.qwandautils.JsonUtils;
import life.genny.qwandautils.QwandaUtils;
import life.genny.qwandautils.GennySettings;
import org.drools.core.spi.KnowledgeHelper;

rule "FILTER_AGENCY"
	ruleflow-group 'SearchFilters'
	salience 9000
	no-loop true
	when
		userToken : GennyToken ( code != "PER_SERVICE" ) 
		serviceToken : GennyToken( code == "PER_SERVICE")
		searchBE: SearchEntity(code matches "SBE_SUMMARY_AGENCY_.*" )
		allowed : Allowed(code == "AGENT")
	
	then
		System.out.println(drools.getRule().getName() + " triggered");
		System.out.println("searchCode   :: " + searchBE.getCode());

		BaseEntityUtils beUtils = new BaseEntityUtils(serviceToken, userToken);

		BaseEntity userBe = beUtils.getBaseEntityByCode(userToken.getUserCode());
		if(userBe == null){
			System.out.println("userBe is null");
			return;
		}

		String agencyCode = userBe.getValue("LNK_AGENCY", null);		
		if(agencyCode == null){
			System.out.println("agencyCode is null");
			return;
		}

		System.out.println("agencyCode   ::   " + agencyCode);
		agencyCode = agencyCode.replace("\"", "").replace("[", "").replace("]", "");
		System.out.println("agencyCode after   ::   " + agencyCode);

		searchBE.addFilter("PRI_CODE", SearchEntity.StringFilter.EQUAL, agencyCode);

		BaseEntity agency = beUtils.getBaseEntityByCode(agencyCode);
		if(agency != null){

			String agencyName = agency.getValue("PRI_NAME",null);
			System.out.println("agencyName   ::   " + agencyName);

			if (agencyName != null && !agencyName.isEmpty()) {
				searchBE.setTitle(agencyName);
			}
		}else{
			System.out.println("agency BE is null");
		}

		/* Create  QDataBaseEntityMessage for SearchEntity */
		QDataBaseEntityMessage msg = new QDataBaseEntityMessage(searchBE);
		msg.setAliasCode("SBE");	
		payload.add(msg); 

		drools.getKnowledgeRuntime().setGlobal("payload", payload); 
end
