package life.genny.rules;
import life.genny.qwanda.message.QDataAnswerMessage;
import life.genny.models.GennyToken;
import life.genny.rules.QRules;
import life.genny.utils.BaseEntityUtils;
import life.genny.qwanda.Answer;
import life.genny.qwanda.entity.BaseEntity;
import life.genny.utils.OutputParam;
import life.genny.qwandautils.KeycloakUtils;
import java.util.UUID;

import java.util.List;
import java.util.ArrayList;

rule "SEND_QUESTION_USER_DATA"
    ruleflow-group 'ScenarioProcessing'
    no-loop true
    salience 15
    when
	 	userToken : GennyToken (code != "PER_SERVICE" )
		serviceToken : GennyToken (code == "PER_SERVICE" )
		output : OutputParam()

     then
		System.out.println(drools.getRule().getName() + ": Rule fired");
 		
 		BaseEntityUtils beUtils = new BaseEntityUtils(userToken);

		beUtils.saveAnswer(new Answer(userToken.getUserCode(), userToken.getUserCode(), "PRI_CURRENT_QUESTION_STATUS", ""));
		beUtils.saveAnswer(new Answer(userToken.getUserCode(), userToken.getUserCode(), "TMP_PREV_ANSWERS", ""));

		System.out.println(drools.getRule().getName() + ": Sending userBE");
		/* SEND USERBE */
		BaseEntity userBe = beUtils.getBaseEntityByCode(userToken.getUserCode());
		QDataBaseEntityMessage userBeMsg = new QDataBaseEntityMessage(userBe);
		userBeMsg.setToken(userToken.getToken());
		userBeMsg.setReplace(true);
		VertxUtils.writeMsg("webcmds", JsonUtils.toJson(userBeMsg));
		
		output.setTypeOfResult("NONE");
  	    output.setResultCode("NONE");  /* dont display anything new */
			
end