package life.genny.rules;
import life.genny.qwanda.message.QDataAnswerMessage;
import life.genny.models.GennyToken;
import life.genny.rules.QRules;
import life.genny.utils.BaseEntityUtils;
import life.genny.qwanda.Answer;
import life.genny.qwanda.entity.BaseEntity;
import life.genny.utils.OutputParam;
import life.genny.qwandautils.KeycloakUtils;
import java.util.UUID;

import java.util.List;
import java.util.ArrayList;

rule "SEND_QUESTION_JSON"
    ruleflow-group 'ScenarioProcessing'
    no-loop true
    salience 10
    when
	 	userToken : GennyToken (code != "PER_SERVICE" )
		serviceToken : GennyToken (code == "PER_SERVICE" )
		questionGroup : String(questionGroup matches "QUE_STT.*")
		output : OutputParam()

     then
		System.out.println(drools.getRule().getName() + ": Rule fired");
		System.out.println(drools.getRule().getName() + ": questionGroup = " + questionGroup);
 		
 		BaseEntityUtils beUtils = new BaseEntityUtils(userToken);

		String code = "DEFAULT";

		code = questionGroup.split("QUE_STT_")[1].split("_GRP")[0];

		try {
			String jsonValue = beUtils.getBaseEntityValueAsString("UNT_" + code + "_CTX_DATA", "PRI_UNITY_SCENE_JSON");
			if (jsonValue != null) {

				String arrayItems = "[\"reactObject\", \"changeQuestionReact\", "+ jsonValue + "]";

				System.out.println(drools.getRule().getName() + " - Sending msg with items: " + arrayItems);

				/* Send SCENE JSON QCmdMessage to FE */
				QCmdMessage cmdMsg = new QCmdMessage("UNITY_EVENT", arrayItems);
				cmdMsg.setToken(beUtils.getGennyToken().getToken());
				String json = JsonUtils.toJson(cmdMsg);
				VertxUtils.writeMsg("webcmds", json);
			}
		} catch (Exception e) {
			System.out.println(drools.getRule().getName() + " - Could not find CTX BE for Question");
		}
		
		output.setTypeOfResult("NONE");
  	    output.setResultCode("NONE");  /* dont display anything new */
			
end