package life.genny.rules;
import life.genny.qwanda.message.QDataAnswerMessage;
import life.genny.models.GennyToken;
import life.genny.rules.QRules;
import life.genny.utils.BaseEntityUtils;
import life.genny.qwanda.Answer;
import life.genny.qwanda.entity.BaseEntity;
import life.genny.utils.OutputParam;
import life.genny.qwandautils.KeycloakUtils;
import java.util.UUID;

import java.util.List;
import java.util.ArrayList;

rule "SETUP_STUDENT"
    ruleflow-group 'InitialiseEntity'
    no-loop true
    salience 1 
    when
	 	userToken : GennyToken (code != "PER_SERVICE" )
		serviceToken : GennyToken (code == "PER_SERVICE" )
		output : OutputParam()
		baseEntityType : String(baseEntityType.equals("Student"))
		newBe : BaseEntity()
 		beUtils : BaseEntityUtils()
		allowed : Allowed(code == "EDU_PRO_REP")
	  
     then
 		System.out.println(drools.getRule().getName()+" : Rule fired" );
 		
		String eduProCode = beUtils.getBaseEntityValueAsString(userToken.getUserCode(), "LNK_EDU_PROVIDER");

		if (eduProCode != null) {
			beUtils.saveAnswer(new Answer(userToken.getUserCode(), newBe.getCode() ,"LNK_EDU_PROVIDER", eduProCode));
		} else {
			System.out.println(drools.getRule().getName()+" : COULD NOT FIND LNK_EDU_PRO FOR USER" );
		}
	
end