package life.genny.rules;
import life.genny.qwanda.message.QDataAnswerMessage;
import life.genny.models.GennyToken;
import life.genny.rules.QRules;
import life.genny.utils.BaseEntityUtils;
import life.genny.qwanda.Answer;
import io.vertx.core.json.JsonObject;
import java.util.Map;
import java.util.HashMap;
import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.List;
import com.google.gson.reflect.TypeToken;
import life.genny.qwandautils.JsonUtils;
import life.genny.qwandautils.KeycloakUtils;
import life.genny.utils.VertxUtils;
import life.genny.utils.TableUtils;
import life.genny.models.TableData;
import life.genny.qwanda.message.QDataBaseEntityMessage;
import life.genny.qwanda.entity.BaseEntity;
import life.genny.qwanda.entity.SearchEntity;
import life.genny.qwanda.Ask;
import life.genny.qwanda.message.QDataAskMessage;
import life.genny.qwanda.utils.OutputParam;
import life.genny.jbpm.customworkitemhandlers.ShowFrame;
import life.genny.models.BaseEntityImport;
import io.vavr.Tuple;
import io.vavr.Tuple2;
import life.genny.utils.ImportUtils;
import life.genny.qwanda.datatype.Allowed;
import life.genny.utils.CapabilityUtils;
import java.util.UUID;
import life.genny.rules.listeners.GennyRuleTimingListener;
import life.genny.utils.TableUtils;


rule "INTERNSHIP_LNK_HOST_COMPANY"
    ruleflow-group 'DataProcessing'
        salience -100
        no-loop true
    when
 	  beUtils : BaseEntityUtils()
 	  allowed : Allowed(code == "USER") 
	  answer : Answer( targetCode matches "BEG_.*" && attributeCode matches "LNK_HOST_COMPANY")   
	  userToken : GennyToken (code != "PER_SERVICE" )
	  serviceToken : GennyToken( code == "PER_SERVICE")
	  ruleDetails : RuleDetails()
	   answersToSave : Answers()
    then
  		System.out.println("Rule -> "+drools.getRule().getName()+" :  user=" + beUtils.getGennyToken().getUserCode()+" : "+answer);
   		
 		String hostCompanyCode = answer.getValue().trim().substring(2,answer.getValue().trim().length()-2);
		BaseEntity hostCompany = beUtils.getBaseEntityByCode(hostCompanyCode);
		String url = hostCompany.getValue("PRI_IMAGE_URL",null);
		if (url != null) {
		
			beUtils.saveAnswer(new Answer(userToken.getUserCode(), answer.getTargetCode(), "PRI_IMAGE_URL", url,false,false));
	
		}
	
		
end
