package life.genny.rules;


import life.genny.qwanda.message.QCmdMessage;
import life.genny.qwanda.message.QBulkMessage;
import life.genny.qwanda.message.QDataBaseEntityMessage;
import life.genny.qwanda.message.QEventMessage;
import life.genny.rules.QRules;
import life.genny.qwandautils.JsonUtils;
import org.apache.logging.log4j.Logger;


import java.util.List;
import java.util.ArrayList;
import life.genny.qwanda.entity.BaseEntity;
import life.genny.qwanda.entity.SearchEntity;
import life.genny.utils.VertxUtils;
import life.genny.utils.BaseEntityUtils;
import life.genny.models.GennyToken;
import org.kie.api.runtime.process.WorkflowProcessInstance;
import life.genny.utils.BaseEntityUtils;
import life.genny.qwandautils.GennySettings;

rule "SBE_TEMPLATE_INTERN"
    ruleflow-group 'GenerateSearches'
     no-loop true
    when
       not  SearchEntity (code == "SBE_TEMPLATE_INTERN")
        serviceToken : GennyToken( code == "PER_SERVICE")
     then
     	System.out.println("   Generate "+drools.getRule().getName() );
     	BaseEntityUtils beUtils = new BaseEntityUtils(serviceToken);

		SearchEntity searchBE = new SearchEntity(drools.getRule().getName(), "Intern Template")
			.addColumn("PRI_NAME", "Name")
			.addColumn("PRI_EMAIL", "Email")
			.addColumn("PRI_MOBILE", "Mobile")
			.addColumn("PRI_STUDENT_ID", "Student Id")
			.addColumn("PRI_ASSOC_EP", "Education Provider")
			.addColumn("PRI_ASSOC_INDUSTRY", "Industry")
			.addColumn("PRI_ASSOC_OCCUPATION", "Specialisation")
			.addColumn("PRI_ASSOC_DURATION", "Duration (Weeks)")
			.addColumn("PRI_ADDRESS_FULL", "Address")
			.addColumn("PRI_CURRENT_COURSE", "Current Course")
			.addColumn("PRI_VIDEO_URL", "Video")
			.addColumn("PRI_CV", "CV")
			.addColumn("PRI_LINKEDIN_URL", "LinkedIn")
			.addColumn("PRI_CAREER_OBJ", "Carrer Objectives")
			.addColumn("PRI_TRANSPORT", "Transport")

			.addColumn("PRI_ASSOC_CURRENT_SOFTWARE", "Current Software")
			.addColumn("PRI_ASSOC_FUTURE_SOFTWARE", "Future Software")
			.addColumn("PRI_PREV_EMPLOYER", "Name of Employer")
			.addColumn("PRI_PREV_JOB_TITLE", "Job Title")

			.addColumn("PRI_IMAGE_URL", " ")

			
			.setDisplayMode("DETAIL_VIEW:CV")
			.setPageStart(0)
			.setPageSize(GennySettings.defaultPageSize);

		searchBE.setRealm(serviceToken.getRealm());
		insert(searchBE);
		VertxUtils.putObject(serviceToken.getRealm(), "", searchBE.getCode(), searchBE, serviceToken.getToken());

end
