package life.genny.rules;


global org.apache.logging.log4j.Logger log;

import life.genny.qwanda.message.QCmdMessage;
import life.genny.qwanda.message.QBulkMessage;
import life.genny.qwanda.message.QDataBaseEntityMessage;
import life.genny.qwanda.message.QEventMessage;
import life.genny.qwanda.message.QDataAskMessage;
import life.genny.rules.QRules;
import io.vertx.core.json.JsonObject;
import life.genny.qwandautils.JsonUtils;
import java.util.List;
import java.util.ArrayList;
import java.util.Set;
import java.util.HashSet;
import life.genny.qwanda.entity.BaseEntity;
import life.genny.qwanda.entity.SearchEntity;
import life.genny.utils.VertxUtils;
import life.genny.utils.BaseEntityUtils;
import life.genny.models.GennyToken;
import org.kie.api.runtime.process.WorkflowProcessInstance;
import life.genny.models.Frame3;
import life.genny.models.Theme;
import life.genny.utils.FrameUtils2;
import life.genny.models.FramePosition;
import life.genny.qwanda.VisualControlType;
import life.genny.utils.RulesUtils;
import life.genny.qwanda.Answer;
import life.genny.qwanda.attribute.Attribute;

rule "PCM_INTERN"
    ruleflow-group 'GeneratePCMs'
       salience 5000 
        no-loop true
    when
      	beUtils : BaseEntityUtils()
	  	serviceToken : GennyToken( code == "PER_SERVICE")
	  	ruleDetails : RuleDetails()
    then
		System.out.println(ruleDetails+" "+drools.getRule().getName()); 

		Map<String,String> attributeMap = new HashMap<String,String>();
		attributeMap.put("PRI_LOC1", "PRI_VIDEO_URL");
		attributeMap.put("PRI_LOC2", "_LNK_INDUSTRY__PRI_NAME");
		attributeMap.put("PRI_LOC3", "_LNK_OCCUPATION__PRI_NAME");
		attributeMap.put("PRI_LOC4", "_LNK_CURRENT_SOFTWARE__PRI_NAME");
		attributeMap.put("PRI_LOC5", "_LNK_FUTURE_SOFTWARE__PRI_NAME");
		attributeMap.put("PRI_LOC6", "PRI_CAREER_OBJ");
		attributeMap.put("PRI_LOC7", "PRI_ASSOC_DURATION");
		attributeMap.put("PRI_LOC8", "_LNK_DAYS_PER_WEEK__PRI_NAME");
		attributeMap.put("PRI_LOC9", "LNK_WHICH_DAYS");

		/*beUtils.addPCMAttributes("PCM Intern Detail", "PCM_INTERN_DETAIL", "TPL_PROFILE_DETAIL_VIEW", attributeMap);*/
		
end
