package life.genny.rules;


import life.genny.qwanda.message.QCmdMessage;
import life.genny.qwanda.message.QBulkMessage;
import life.genny.qwanda.message.QDataBaseEntityMessage;
import life.genny.qwanda.message.QEventMessage;
import life.genny.rules.QRules;
import life.genny.qwandautils.JsonUtils;
import org.apache.logging.log4j.Logger;


import java.util.List;
import java.util.ArrayList;
import life.genny.qwanda.entity.BaseEntity;
import life.genny.qwanda.entity.SearchEntity;
import life.genny.utils.VertxUtils;
import life.genny.utils.BaseEntityUtils;
import life.genny.models.GennyToken;
import org.kie.api.runtime.process.WorkflowProcessInstance;
import life.genny.utils.BaseEntityUtils;
import life.genny.qwandautils.GennySettings;

rule "SBE_TEMPLATE_INTERNSHIP"
    ruleflow-group 'GenerateSearches'
     no-loop true
    when
       not  SearchEntity (code == "SBE_TEMPLATE_INTERNSHIP")
        serviceToken : GennyToken( code == "PER_SERVICE")
     then
     	System.out.println("   Generate "+drools.getRule().getName() );
     	BaseEntityUtils beUtils = new BaseEntityUtils(serviceToken);

		SearchEntity searchBE = new SearchEntity(drools.getRule().getName(), "Internship Detail View")
			.addColumn("PRI_NAME", "Name")
			.addColumn("PRI_ASSOC_HC", "Host Company")
			.addColumn("PRI_ADDRESS_FULL", "Address")
			.addColumn("PRI_ASSOC_HCR", "Host Company Rep")
			.addColumn("PRI_ASSOC_SUPERVISOR", "Intern Supervisor")
			.addColumn("PRI_ASSOC_INDUSTRY", "Industry")
			.addColumn("PRI_ASSOC_OCCUPATION", "Specialisation")
			.addColumn("PRI_ROLES_AND_RESPONSIBILITIES", "Roles and Responsibilities")
			.addColumn("PRI_BASE_LEARNING_OUTCOMES", "Base Learning Outcomes")
			.addColumn("PRI_ASSOC_NUM_INTERNS", "Number of Interns")
			.addColumn("PRI_VIDEO_URL", "Video")
			.addColumn("PRI_SPECIFIC_LEARNING_OUTCOMES", "Soft & Critical Skills Learning Outcomes")
			.addColumn("PRI_WHICH_DAYS_STRIPPED", "Days of Internship")
			.addColumn("PRI_DRESS_CODE", "Dress Code")
			.addColumn("PRI_WORKSITE", "Internship Type")
			.addColumn("PRI_IMAGE_URL", " ")
			.addColumn("PRI_INTERNSHIP_START_DATE", "Internship Available From")
			.setDisplayMode("DETAIL_VIEW:INTERNSHIP")
			.setPageStart(0)
			.setPageSize(GennySettings.defaultPageSize);

		searchBE.setRealm(serviceToken.getRealm());
		insert(searchBE);
		VertxUtils.putObject(serviceToken.getRealm(), "", searchBE.getCode(), searchBE, serviceToken.getToken());

end
