package life.genny.rules;


import life.genny.qwanda.message.QCmdMessage;
import life.genny.qwanda.message.QBulkMessage;
import life.genny.qwanda.message.QDataBaseEntityMessage;
import life.genny.qwanda.message.QEventMessage;
import life.genny.rules.QRules;
import life.genny.qwandautils.JsonUtils;
import org.apache.logging.log4j.Logger;


import java.util.List;
import java.util.ArrayList;
import life.genny.qwanda.entity.BaseEntity;
import life.genny.qwanda.entity.SearchEntity;
import life.genny.utils.VertxUtils;
import life.genny.utils.BaseEntityUtils;
import life.genny.models.GennyToken;
import org.kie.api.runtime.process.WorkflowProcessInstance;
import life.genny.utils.BaseEntityUtils;
import life.genny.qwandautils.GennySettings;

rule "SBE_INTERNSHIP"
    ruleflow-group 'GenerateSearches'
     no-loop true
    when
       not  SearchEntity (code == "SBE_INTERNSHIP")
        serviceToken : GennyToken( code == "PER_SERVICE")
     then
     	System.out.println("   Generate "+drools.getRule().getName() );
     	BaseEntityUtils beUtils = new BaseEntityUtils(serviceToken);

		SearchEntity searchBE = new SearchEntity(drools.getRule().getName(), "Internship Detail View")
			.addFilter("PRI_STATUS", SearchEntity.StringFilter.EQUAL, "Active")

			/* Media & Uploads */
			.addColumn("PRI_IMAGE_URL", " ")
			.addColumn("PRI_VIDEO_URL", "Video")
			.addAssociatedColumn("LNK_HOST_COMPANY", "PRI_LINKEDIN_URL", "Company LinkedIn")

			/*Internship Details*/
			.addColumn("PRI_NAME", "Internship Name")
			.addColumn("PRI_ASSOC_OCCUPATION", "Specialisation")
			.addColumn("PRI_ASSOC_INDUSTRY", "Industry")
			.addAssociatedColumn("LNK_WORKSITE_SELECT", "PRI_NAME", "Internship Type")
			.addColumn("PRI_INTERNSHIP_START_DATE", "Internship Available From")
			.addColumn("PRI_WHICH_DAYS_STRIPPED", "Days of Internship")
			.addColumn("PRI_BUSINESS_HOURS", "Business Hours")
			.addAssociatedColumn("LNK_DRESS_CODE", "PRI_NAME", "Dress Code")
			.addColumn("PRI_ASSOC_NUM_INTERNS", "Available Positions")
			.addColumn("PRI_INTERNSHIP_DETAILS", "Intership Overview")
			.addColumn("PRI_ROLES_AND_RESPONSIBILITIES", "Roles and Responsibilities")
			.addColumn("PRI_BASE_LEARNING_OUTCOMES", "Base Learning Outcomes")
			.addColumn("PRI_SPECIFIC_LEARNING_OUTCOMES", "Specific Learning Outcomes")
			.addAssociatedColumn("LNK_SOFTWARE", "PRI_NAME", "Software used during the internship")

			/*Company Details*/
			.addAssociatedColumn("LNK_HOST_COMPANY", "PRI_NAME", "Host Company")
			.addColumn("PRI_ADDRESS_FULL", "Address")
			.addAssociatedColumn("LNK_HOST_COMPANY", "LNK_COMPANY_INDUSTRY", "PRI_NAME", "Company Industry")
			.addAssociatedColumn("LNK_HOST_COMPANY", "PRI_COMPANY_DESCRIPTION", "About the Company")
			.addAssociatedColumn("LNK_HOST_COMPANY", "PRI_ADDRESS_LATITUDE", "Lat")
			.addAssociatedColumn("LNK_HOST_COMPANY", "PRI_ADDRESS_LONGITUDE", "Lng")

			/*Supervisor Details*/
			.addAssociatedColumn("LNK_INTERN_SUPERVISOR", "PRI_IMAGE_URL", "Supervisor Profile Photo")
			.addColumn("PRI_ASSOC_SUPERVISOR", "Supervisor Name")
			.addAssociatedColumn("LNK_INTERN_SUPERVISOR", "PRI_JOB_TITLE", "Position")
			.addAssociatedColumn("LNK_INTERN_SUPERVISOR", "PRI_EMAIL", "Email")
			.addAssociatedColumn("LNK_INTERN_SUPERVISOR", "PRI_MOBILE", "Phone Number")
			.addAssociatedColumn("LNK_INTERN_SUPERVISOR", "PRI_LINKEDIN_URL", "LinkedIn")
			.addAssociatedColumn("LNK_INTERN_SUPERVISOR", "PRI_BIO", "About the Supervisor")


			.setDisplayMode("DETAIL_VIEW:INTERNSHIP")
			.setPageStart(0)
			.setPageSize(GennySettings.defaultPageSize);

		searchBE.setRealm(serviceToken.getRealm());
		insert(searchBE);
		VertxUtils.putObject(serviceToken.getRealm(), "", searchBE.getCode(), searchBE, serviceToken.getToken());

end
