package life.genny.rules;

import java.io.IOException;

global life.genny.qwanda.message.QBulkMessage payload;

import life.genny.qwanda.message.QDataAnswerMessage;
import life.genny.models.GennyToken;
import life.genny.rules.QRules;
import life.genny.utils.BaseEntityUtils;
import life.genny.utils.CapabilityUtils;
import life.genny.qwanda.Answer;
import java.util.List;
import java.util.ArrayList;
import life.genny.model.OutputParamTreeSet;
import life.genny.qwanda.entity.BaseEntity;
import life.genny.qwanda.message.QDataBaseEntityMessage;
import life.genny.qwanda.message.QBulkMessage;
import life.genny.utils.TableUtils;
import life.genny.qwanda.entity.SearchEntity;
import life.genny.qwanda.attribute.EntityAttribute;
import life.genny.qwandautils.JsonUtils;
import life.genny.qwandautils.QwandaUtils;
import life.genny.qwandautils.GennySettings;
import org.drools.core.spi.KnowledgeHelper;

rule "FILTER_APPLICATION_HC_REP_ACCEPT_REJECT"
	ruleflow-group 'SearchFilters'
	salience 10000
	no-loop true
	when
		userToken : GennyToken ( code != "PER_SERVICE" ) 
		searchBE: SearchEntity(code matches "SBE_APPLICATION_.*" )
		allowed: Allowed(code == "HOST_CPY_REP" )
		beUtils : BaseEntityUtils( )
	
	then
		System.out.println(drools.getRule().getName() + " triggered");
		
		System.out.println("searchCode   :: " + searchBE.getCode());

		String applicationCode = null;

		/* Find the targeted Internship code */
		for (EntityAttribute attr : searchBE.getBaseEntityAttributes()) {
			if (attr.getAttributeCode().equals("PRI_CODE") && attr.getAttributeName().equals("_EQ_")) {
				applicationCode = attr.getValue();
			}
		}

		if (applicationCode == null) {
			System.out.println("ApplicationCode is NULL");
			return;
		}

		BaseEntity application = beUtils.getBaseEntityByCode(applicationCode);
		String appHostCompany = application.getValue("LNK_HOST_COMPANY", null);
		String userHostCompany = beUtils.getBaseEntityValueAsString(userToken.getUserCode(), "LNK_HOST_COMPANY");

		if (appHostCompany == null || userHostCompany == null) {
			System.out.println("appHostCompany = " + appHostCompany);
			System.out.println("userHostCompany = " + appHostCompany);
			System.out.println("Either appHostCompany or userHostCompany is NULL");
			return;
		}
		
		/* Ensure this user is with the correct HC */
		if (!appHostCompany.equals(userHostCompany)) {
			System.out.println("This User does not have permission to view these actions... Aborting!");
			return;
		}

		String appStatus = application.getValue("PRI_STATUS", null);

		if (appStatus == null) {
			System.out.println("Application PRI_STATUS is NULL");
			return;
		}

		if (appStatus.equals("SHORTLISTED")) {
			searchBE.addAction("PRI_EVENT_ACCEPT_SHORTLIST", "Accept");
			searchBE.addAction("PRI_EVENT_REJECT_SHORTLIST", "Reject");
		}

		/* Create  QDataBaseEntityMessage for SearchEntity */
		QDataBaseEntityMessage msg = new QDataBaseEntityMessage(searchBE);
		msg.setAliasCode("SBE");	
		payload.add(msg); 

		drools.getKnowledgeRuntime().setGlobal("payload", payload); 
		retract(allowed); 
end
