package life.genny.rules;


import life.genny.qwanda.message.QCmdMessage;
import life.genny.qwanda.message.QBulkMessage;
import life.genny.qwanda.message.QDataBaseEntityMessage;
import life.genny.qwanda.message.QEventMessage;
import life.genny.rules.QRules;
import life.genny.qwandautils.JsonUtils;
import org.apache.logging.log4j.Logger;
import java.util.List;
import java.util.ArrayList;
import life.genny.qwanda.entity.BaseEntity;
import life.genny.qwanda.entity.SearchEntity;
import life.genny.utils.VertxUtils;
import life.genny.utils.BaseEntityUtils;
import life.genny.models.GennyToken;
import org.kie.api.runtime.process.WorkflowProcessInstance;
import life.genny.utils.BaseEntityUtils;
import life.genny.qwandautils.GennySettings;

rule "SBE_SUMMARY_INTERVIEWS"
   ruleflow-group 'GenerateSearches'
   no-loop true
   when
      not  SearchEntity (code == "SBE_SUMMARY_INTERVIEWS")
      serviceToken : GennyToken( code == "PER_SERVICE")
   then
     	System.out.println("   Generate "+drools.getRule().getName() );

      SearchEntity searchBE = new SearchEntity(drools.getRule().getName(), "Upcoming Interviews")
                              .addSort("PRI_INTERVIEW_START_DATETIME", "Interview Date Time", SearchEntity.Sort.ASC)
                              .addFilter("PRI_CODE", SearchEntity.StringFilter.LIKE, "APP_%")
                              .addFilter("PRI_STATUS", SearchEntity.StringFilter.EQUAL, "INTERVIEWED")
                              .addFilter("PRI_DISABLED", false)

                              /* Columns */
                              /* .addColumn("PRI_INTERN_NAME", "Name") */
                              .addAssociatedColumn("PRI_INTERN_CODE", "PRI_NAME", "Name")
                              .addColumn("PRI_TITLE", "Internship")
                              .addColumn("PRI_INTERVIEW_START_DATETIME", "Interview Date")
                              .addColumn("PRI_INTERVIEW_TYPE", "Interview Type")
                              
                              /* Actions */
                              .addAction("PRI_EVENT_VIEW_APPLICATION", "View Application")
                              .addAction("PRI_EVENT_VIEW", "View Profile")
                              
                              /* Display Mode */
                              .setDisplayMode("dashboard_search")
                              .setPageStart(0).setPageSize(10);

      searchBE.setRealm(serviceToken.getRealm());

      insert(searchBE);
      VertxUtils.putObject(serviceToken.getRealm(), "", searchBE.getCode(), searchBE, serviceToken.getToken());

end
