package life.genny.rules;


import life.genny.qwanda.message.QCmdMessage;
import life.genny.qwanda.message.QBulkMessage;
import life.genny.qwanda.message.QDataBaseEntityMessage;
import life.genny.qwanda.message.QEventMessage;
import life.genny.rules.QRules;
import life.genny.qwandautils.JsonUtils;
import org.apache.logging.log4j.Logger;
import java.util.List;
import java.util.ArrayList;
import life.genny.qwanda.entity.BaseEntity;
import life.genny.qwanda.entity.SearchEntity;
import life.genny.utils.VertxUtils;
import life.genny.utils.BaseEntityUtils;
import life.genny.models.GennyToken;
import org.kie.api.runtime.process.WorkflowProcessInstance;
import life.genny.utils.BaseEntityUtils;
import life.genny.qwandautils.GennySettings;

rule "SBE_SUMMARY_HCRS"
   ruleflow-group 'GenerateSearches'
   no-loop true
   when
      not  SearchEntity (code == "SBE_SUMMARY_HCRS")
      serviceToken : GennyToken( code == "PER_SERVICE")
   then
     	System.out.println("   Generate "+drools.getRule().getName() );

      SearchEntity searchBE =  new SearchEntity(drools.getRule().getName(), "Host Company Representatives")
								/* Sorts */
								.addSort("PRI_NAME","Name",SearchEntity.Sort.ASC)
								.addSort("PRI_STATUS","Status",SearchEntity.Sort.ASC)
								.addSort("PRI_ASSOC_HC","Company",SearchEntity.Sort.ASC)

								/* Filters */
								.addFilter("PRI_CODE", SearchEntity.StringFilter.LIKE, "PER_%")
								.addFilter("PRI_IS_HOST_CPY_REP", true)

								/* Columns */
								.addColumn("PRI_NAME", "Name")
								.addColumn("PRI_STATUS", "Status")

								/* Actions */
								.addAction("PRI_EVENT_VIEW", "View")
								.addSearchAction("PRI_EVENT_QUE_HOST_CPY_REP_MENU", "Add")
								.addSearchAction("PRI_EVENT_QUE_TREE_ITEM_HCRS", "View")

								/* Display Mode */
								.setDisplayMode("dashboard_search")
								.setPageStart(0).setPageSize(10);

      searchBE.setRealm(serviceToken.getRealm());

      insert(searchBE);
      VertxUtils.putObject(serviceToken.getRealm(), "", searchBE.getCode(), searchBE, serviceToken.getToken());

end
