package life.genny.rules;

import java.io.IOException;

global life.genny.qwanda.message.QBulkMessage payload;

import life.genny.qwanda.message.QDataAnswerMessage;
import life.genny.models.GennyToken;
import life.genny.rules.QRules;
import life.genny.utils.BaseEntityUtils;
import life.genny.utils.CapabilityUtils;
import life.genny.qwanda.Answer;
import java.util.List;
import java.util.ArrayList;
import life.genny.model.OutputParamTreeSet;
import life.genny.qwanda.entity.BaseEntity;
import life.genny.qwanda.message.QDataBaseEntityMessage;
import life.genny.qwanda.message.QBulkMessage;
import life.genny.utils.TableUtils;
import life.genny.qwanda.entity.SearchEntity;
import life.genny.qwandautils.JsonUtils;
import life.genny.qwandautils.QwandaUtils;
import life.genny.qwandautils.GennySettings;
import org.drools.core.spi.KnowledgeHelper;

rule "FILTER_METORING_MEETINGS_MENTEE"
	ruleflow-group 'SearchFilters'
	salience 10000
	no-loop true
	when
		userToken : GennyToken ( code != "PER_SERVICE" )
		serviceToken : GennyToken( code == "PER_SERVICE")
		searchBE: SearchEntity(	code matches "SBE_MENTORING_MEETINGS_.*")
		allowed : Allowed(code == "MENTEE")

	then
		System.out.println(drools.getRule().getName() + " triggered");
		System.out.println("searchCode   :: " + searchBE.getCode());

		BaseEntityUtils beUtils = new BaseEntityUtils(serviceToken, userToken);

		BaseEntity userBe = beUtils.getBaseEntityByCode(userToken.getUserCode());
		if(userBe == null){
			System.out.println("userBe is null");
			return;
		}

		String applicationCode = userBe.getValue("LNK_APPLICATION", null);
		if(applicationCode == null){
			System.out.println("applicationCode is null");
			return;
		}

		System.out.println("applicationCode   ::   " + applicationCode);

		searchBE.addFilter("LNK_APPLICATION", SearchEntity.StringFilter.EQUAL, applicationCode);

		/* Create  QDataBaseEntityMessage for SearchEntity */
		QDataBaseEntityMessage msg = new QDataBaseEntityMessage(searchBE);
		msg.setAliasCode("SBE");
		payload.add(msg);

		drools.getKnowledgeRuntime().setGlobal("payload", payload);
end
