package life.genny.rules;


import life.genny.qwanda.message.QCmdMessage;
import life.genny.qwanda.message.QBulkMessage;
import life.genny.qwanda.message.QDataBaseEntityMessage;
import life.genny.qwanda.message.QEventMessage;
import life.genny.rules.QRules;
import life.genny.qwandautils.JsonUtils;
import org.apache.logging.log4j.Logger;


import java.util.List;
import java.util.ArrayList;
import life.genny.qwanda.entity.BaseEntity;
import life.genny.qwanda.entity.SearchEntity;
import life.genny.utils.VertxUtils;
import life.genny.utils.BaseEntityUtils;
import life.genny.models.GennyToken;
import org.kie.api.runtime.process.WorkflowProcessInstance;
import life.genny.utils.BaseEntityUtils;
import life.genny.qwandautils.GennySettings;

rule "SBE_SUMMARY_MENTORS"
    ruleflow-group 'GenerateSearches'
     no-loop true
    when
       not  SearchEntity (code == "SBE_SUMMARY_MENTORS")
        serviceToken : GennyToken( code == "PER_SERVICE")
    then
     	System.out.println("   Generate "+drools.getRule().getName() );
     	BaseEntityUtils beUtils = new BaseEntityUtils(serviceToken);

		SearchEntity searchBE = new SearchEntity(drools.getRule().getName(), "Our Mentors")
			.addFilter("PRI_IS_MENTOR", true)
			.addFilter("PRI_DISABLED", false)
			/*.addFilter("PRI_STATUS", SearchEntity.StringFilter.LIKE, "AVAILABLE")*/

			/* Table Columns */
			.addColumn("PRI_FIRSTNAME", "Firstname")
			.addColumn("PRI_LASTNAME", "Lastname")
			.addColumn("PRI_NAME", "Name")
            .addColumn("PRI_EMAIL", "Email")
            .addColumn("PRI_MOBILE", "Mobile")
            .addColumn("PRI_GENDER", "Gender")
            .addColumn("PRI_LINKEDIN_PROFILE_URL", "LinkedIn")
			/*.addColumn("LNK_SELECT_COUNTRY", "Country of origin")*/
			/*.addColumn("PRI_TRAINING_STATUS", "Training Status")*/
            .addColumn("PRI_VIDEO_URL", "Videourl")
			.addColumn("PRI_USER_PROFILE_PICTURE", "Profile Picture")
			/*.addColumn("PRI_STATUS", "Status")*/

            .addAssociatedColumn("LNK_MM_INDUSTRY", "PRI_NAME", "Industry")
			.addAssociatedColumn("LNK_SELECT_COUNTRY", "PRI_NAME", "Location")
			.addAssociatedColumn("LNK_SELECT_ORIGIN_COUNTRY", "PRI_NAME", "Country of origin")
            .addAssociatedColumn("LNK_MENTOR_PREV_EXP", "PRI_NAME", "Mentor Previous Experience")
            .addAssociatedColumn("LNK_HOBBIES_INTEREST", "PRI_NAME", "Hobbies and Interest")
            .addAssociatedColumn("LNK_MENTOR_CLUB", "PRI_NAME", "Club Name")
			.addAssociatedColumn("LNK_OUTPUTS_OF_MENTORING_PROGRAM", "PRI_NAME", "Mentoring Program Output")
			

			/* Actions */
			.addSearchAction("PRI_EVENT_QUE_TREE_ITEM_MENTORS", "View")

			/* Display Mode */
			.setDisplayMode("our_mentors")
			.setPageStart(0).setPageSize(GennySettings.defaultPageSize);

		searchBE.setRealm(serviceToken.getRealm());
		insert(searchBE);
		VertxUtils.putObject(serviceToken.getRealm(), "", searchBE.getCode(), searchBE, serviceToken.getToken());

end
