package life.genny.gadaq;

import life.genny.gadaq.utils.KogitoUtils;

ruleflow-group "AddItem"

rule AddPerson 
when
	prefix : String( prefix == "PER" )
then
	System.out.println("PER triggered");
	retract(prefix);
	/* insert("personLifecycle") */
end

rule AddCompany 
when
	prefix : String( prefix == "CPY" )
then
	System.out.println("CPY triggered");
	retract(prefix);
	/* insert("companyLifecycle") */
end

rule Default
salience 0
when
	prefix : String()
then
	System.out.println("No Add Item workflow for prefix " + prefix);
	retract(prefix);
end

