package life.genny.rules;


import life.genny.qwanda.message.QCmdMessage;
import life.genny.qwanda.message.QBulkMessage;
import life.genny.qwanda.message.QDataBaseEntityMessage;
import life.genny.qwanda.message.QEventMessage;
import life.genny.rules.QRules;
import life.genny.qwandautils.JsonUtils;
import org.apache.logging.log4j.Logger;


import java.util.List;
import java.util.ArrayList;
import life.genny.qwanda.entity.BaseEntity;
import life.genny.qwanda.entity.SearchEntity;
import life.genny.utils.VertxUtils;
import life.genny.utils.BaseEntityUtils;
import life.genny.models.GennyToken;
import org.kie.api.runtime.process.WorkflowProcessInstance;
import life.genny.utils.BaseEntityUtils;
import life.genny.qwandautils.GennySettings;

rule "SBE_HOST_CPY_REP"
    ruleflow-group 'GenerateSearches'
     no-loop true
    when
       not  SearchEntity (code == "SBE_HOST_CPY_REP")
        serviceToken : GennyToken( code == "PER_SERVICE")
     then
     	System.out.println("   Generate "+drools.getRule().getName() );
     	BaseEntityUtils beUtils = new BaseEntityUtils(serviceToken);

		SearchEntity searchBE = new SearchEntity(drools.getRule().getName(), "Host Company Representative")
			.addSort("PRI_NAME","Name",SearchEntity.Sort.ASC)
			.addSort("PRI_STATUS","Status",SearchEntity.Sort.ASC)
			.addSort("PRI_ASSOC_HC","Company",SearchEntity.Sort.ASC)
			.addSort("PRI_JOB_TITLE","Job Title",SearchEntity.Sort.ASC)
			.addFilter("PRI_CODE", SearchEntity.StringFilter.LIKE, "PER_%")
			.addFilter("PRI_IS_HOST_CPY_REP", true)
			
			/* Media */
			.addColumn("PRI_IMAGE_URL", " ")
			
			/* Supervisor Details */
			.addColumn("PRI_NAME", "Name")
			.addColumn("PRI_JOB_TITLE", "Job Title")
			.addColumn("PRI_EMAIL", "Email")
			.addColumn("PRI_MOBILE", "Phone Number")
			.addColumn("PRI_LINKEDIN_URL", "Linkedin")
			.addColumn("PRI_BIO", "About Myself")
			.addColumn("PRI_SUPER_QUALIFICATION", "Qualifications")
			
			/*Company*/
			.addColumn("PRI_ASSOC_HC", "Company")
			.addAssociatedColumn("LNK_HOST_COMPANY", "PRI_IMAGE_URL", "Company Logo")
			
			.addLinkedSearch("SBE_LINKED_INTERNSHIP_OF_SUPERVISOR", "My Internship Opportunities")

			.setDisplayMode("DETAIL_VIEW:REP")

			.setPageStart(0).setPageSize(GennySettings.defaultPageSize);

		searchBE.setRealm(serviceToken.getRealm());
		insert(searchBE);
		VertxUtils.putObject(serviceToken.getRealm(), "", searchBE.getCode(), searchBE, serviceToken.getToken());

end
