package life.genny.rules;
import life.genny.models.GennyToken;
import life.genny.rules.QRules;
import life.genny.utils.BaseEntityUtils;
import life.genny.qwanda.Answer;
import life.genny.qwanda.entity.BaseEntity;
import life.genny.qwanda.utils.OutputParam;
import life.genny.utils.TaskUtils;
import java.util.List;
import java.util.ArrayList;
import life.genny.utils.QuestionUtils;

rule "HELPER_LNK_CLUB"
	ruleflow-group 'DataProcessing'
	salience 500
	no-loop true
	when
		userToken : GennyToken (code != "PER_SERVICE" )
		serviceToken : GennyToken (code == "PER_SERVICE" )
		answer : Answer( attributeCode == "LNK_CLUB" )
		beUtils : BaseEntityUtils()

	then
		System.out.println(drools.getRule().getName()+": Rule fired");

		/* Get Target User BE */
 		String targetCode = answer.getTargetCode();
 		System.out.println(drools.getRule().getName() + ":: targetCode = " + targetCode);
 		String value = answer.getValue();
 		System.out.println(drools.getRule().getName() + ":: value = " + value);
		String formattedClubValue = value.replace("\"", "").replace("[", "").replace("]", "");
		BaseEntity clubBe = beUtils.getBaseEntityByCode(formattedClubValue);
		System.out.println(drools.getRule().getName() + ":: clubBe Code = " + clubBe.getCode());
		String clubPresident = clubBe.getValue("LNK_CLUB_PRESIDENT",null);



		if(clubPresident != null)
		{
			System.out.println(drools.getRule().getName() + ":: INSIDE IF");
			QCmdMessage toastMsg = new QCmdMessage("TOAST", "INFO");
			toastMsg.setMessage("Club already has club president");
			toastMsg.setToken(beUtils.getGennyToken().getToken());
			toastMsg.setSend(true);
			VertxUtils.writeMsg("webcmds", toastMsg);
			/* Disable Submit */
			Ask ask = VertxUtils.getObject(serviceToken.getRealm(), "", "QUE_QA_CLUB_PRESIDENT_MENU", Ask.class, serviceToken.getToken());

			for (Ask childAsk : ask.getChildAsks()[0].getChildAsks()) {
				if (childAsk.getQuestionCode().contains("QUE_SUBMIT")) {
					childAsk.setDisabled(false);
				}
			}
		}
		else
		{
				beUtils.saveAnswer(new Answer(userToken.getUserCode(), clubBe.getCode() ,"LNK_CLUB_PRESIDENT", targetCode));
		}
end
