package life.genny.rules;
import life.genny.qwanda.message.QDataAnswerMessage;
import life.genny.models.GennyToken;
import life.genny.rules.QRules;
import life.genny.utils.BaseEntityUtils;
import life.genny.qwanda.Answer;
import life.genny.qwanda.entity.BaseEntity;
import life.genny.qwanda.utils.OutputParam;

import java.util.List;
import java.util.ArrayList;

rule "SET_APPLIED"
    ruleflow-group 'MoveBucket'
    no-loop true
    salience 1 
    when
	 	userToken : GennyToken (code != "PER_SERVICE" )
		serviceToken : GennyToken (code == "PER_SERVICE" )
		newApplication : BaseEntity()
		/*controlSignalCode : String("FIRST".equals(controlSignalCode))*/
	  
     then
 		System.out.println("##################################### SET_APPLIED: Rule fired" );
 		
 		Answer answer = new Answer(userToken.getUserCode(), newApplication.getCode(),"PRI_STATUS","APPLIED");
 		BaseEntityUtils beUtils = new BaseEntityUtils(userToken);
 		beUtils.saveAnswer(answer);
 		
 		System.out.println("##################################### SET_APPLIED: ANSWER = " +answer);
 		System.out.println("##################################### SET_APPLIED: NEW_APPLICATION = " + newApplication); 
 		
 		retract(newApplication)
 		/*retract(controlSignalCode)*/


		
end

